[pytest]
minversion = 6.0
addopts = --nbmake --nbmake-timeout=1200 -v
log_cli = true
testpaths =
    notebooks/test_notebook.py
    notebooks/example_usage.ipynb
    notebooks/example_usage_simple.ipynb
    notebooks/example_searches_test.ipynb
