# drug_names.py

# List of drug names
drug_names = [
    "Aspirin",
    "Ibuprofen",
    "Paracetamol",
    "Acetaminophen",
    "Penicillin",
    "Amoxicillin",
    "Ciprofloxacin",
    "Lisinopril",
    "Metformin",
    "Atorvastatin",
    "Doxycycline",
    "Fluoxetine",
    "Alprazolam",
    "Omeprazole",
    "Azithromycin",
    "Hydrocodone",
    "Levothyroxine",
    "Metoprolol",
    "Tramadol",
    "Warfarin",
    "Losartan",
    "Gabapentin",
    "Furosemide",
    "Prednisone",
    "Cephalexin",
    "Cyclobenzaprine",
    "Oxycodone",
    "Escitalopram",
    "Trazodone",
    "Clonazepam",
    "Amphetamine",
    "Morphine",
    "Pregabalin",
    "Methadone",
    "Methylphenidate",
    "Hydromorphone",
    "Sertraline",
    "Duloxetine",
    "Citalopram",
    "Bupropion",
    "Venlafaxine",
    "Amitriptyline",
    "Naproxen",
    "Fentanyl",
    "Risperidone",
    "Quetiapine",
    "Lorazepam",
    "Diazepam",
    "Carisoprodol",
    "Oxazepam",
    "Temazepam",
    "Clonidine",
    "Mirtazapine",
    "Hydroxyzine",
    "Benzodiazepine",
    "Chlorpromazine",
    "Pantoprazole",
    "Loratadine",
    "Esomeprazole",
    "Esomeprazole",
    "Ranitidine",
    "Promethazine",
    "Trazodone",
    "Fexofenadine",
    "Desloratadine",
    "Codeine",
    "Cetirizine",
    "Diphenhydramine",
    "Montelukast",
    "Mometasone",
    "Fluticasone",
    "Salmeterol",
    "Fluticasone",
    "Budesonide",
    "Triamcinolone",
    "Albuterol",
    "Methylprednisolone",
    "Prednisolone",
    "Levalbuterol",
    "Terbutaline",
    "Zafirlukast",
    "Azelastine",
    "Doxylamine",
    "Theophylline",
    "Ipratropium",
    "Beclometasone",
    "Ciclesonide",
    "Nasaline",
    "Salbutamol",
    "Epinephrine",
    "Flunisolide",
    "Ipratropium",
    "Omalizumab",
    "Budesonide",
    "Mometasone",
    "Fluticasone",
    "Salmeterol",
    "Fluticasone",
    "Budesonide",
    "Triamcinolone",
    "Albuterol",
    "Methylprednisolone",
    "Prednisolone",
    "Levalbuterol",
    "Terbutaline",
    "Zafirlukast",
    "Azelastine",
    "Doxylamine",
    "Theophylline",
    "Ipratropium",
    "Beclometasone",
    "Ciclesonide",
    "Nasaline",
    "Salbutamol",
    "Epinephrine",
    "Flunisolide",
    "Ipratropium",
    "Omalizumab",
]

# diagnostic_names.py

# List of diagnostic test names
diagnostic_names = [
    "Blood Test",
    "MRI Scan",
    "CT Scan",
    "X-ray",
    "Ultrasound",
    "Electrocardiogram (ECG)",
    "Echocardiogram",
    "Colonoscopy",
    "Endoscopy",
    "Mammogram",
    "Biopsy",
    "Lumbar Puncture",
    "Electroencephalogram (EEG)",
    "Pap Smear",
    "Bone Density Test",
    "Thyroid Function Test",
    "Liver Function Test",
    "Kidney Function Test",
    "Pregnancy Test",
    "Stress Test",
    "Spirometry",
    "Colon Cancer Screening",
    "Prostate-Specific Antigen (PSA) Test",
    "HIV Test",
    "Stool Test",
    "Sputum Culture",
    "Skin Allergy Test",
    "Cardiac Catheterization",
    "Arteriogram",
    "Genetic Testing",
    "Serum Electrolytes Test",
    "C-Reactive Protein (CRP) Test",
    "D-dimer Test",
    "Lipid Profile",
    "Thyroid Stimulating Hormone (TSH) Test",
    "Hemoglobin A1c (HbA1c) Test",
    "Troponin Test",
    "BUN (Blood Urea Nitrogen) Test",
    "Creatinine Test",
    "Prothrombin Time (PT) Test",
    "Activated Partial Thromboplastin Time (aPTT) Test",
    "Complete Blood Count (CBC)",
    "Basic Metabolic Panel (BMP)",
    "Comprehensive Metabolic Panel (CMP)",
    "Thyroid Panel",
    "Liver Panel",
    "Renal Panel",
    "Urinalysis",
    "Stool Culture",
    "Semen Analysis",
    "Colonoscopy",
    "Upper GI Endoscopy",
    "Sigmoidoscopy",
    "Flexible Sigmoidoscopy",
    "Hysteroscopy",
    "Cystoscopy",
    "Laparoscopy",
    "Biopsy",
    "Fine Needle Aspiration (FNA)",
    "Percutaneous Biopsy",
    "Core Needle Biopsy",
    "Excisional Biopsy",
    "Frozen Section Biopsy",
    "Endometrial Biopsy",
    "Bone Marrow Biopsy",
    "Liver Biopsy",
    "Skin Biopsy",
    "Muscle Biopsy",
    "Lymph Node Biopsy",
    "Open Biopsy",
    "Closed Biopsy",
    "Punch Biopsy",
    "Scalp Biopsy",
    "Nail Bed Biopsy",
    "Corneal Biopsy",
    "Eye Biopsy",
    "Cervical Biopsy",
    "Esophageal Biopsy",
    "Gastric Biopsy",
    "Renal Biopsy",
    "Kidney Biopsy",
    "Gallbladder Biopsy",
    "Pancreatic Biopsy",
    "Thyroid Biopsy",
    "Testicular Biopsy",
    "Ovarian Biopsy",
    "Adrenal Biopsy",
    "Adenoid Biopsy",
    "Bronchial Biopsy",
    "Lung Biopsy",
    "Pulmonary Biopsy",
    "Pleural Biopsy",
    "Pericardial Biopsy",
    "Cardiac Biopsy",
    "Myocardial Biopsy",
    "Ventricular Biopsy",
    "Atrial Biopsy",
    "Transbronchial Biopsy",
    "Mediastinal Biopsy",
    "Neck Biopsy",
    "Axillary Biopsy",
    "Breast Biopsy",
    "Breast Cancer Biopsy",
    "Breast Core Biopsy",
    "Breast Fine Needle Aspiration (FNA) Biopsy",
    "Breast Needle Biopsy",
    "Breast Open Biopsy",
    "Breast Punch Biopsy",
    "Breast Scalp Biopsy",
    "Breast Skin Biopsy",
    "Breast Stereotactic Biopsy",
    "Breast Surgical Biopsy",
    "Breast Vacuum-Assisted Biopsy",
    "Breast Wire Localization Biopsy",
    "Mammography",
    "Digital Mammography",
    "3D Mammography",
    "Breast Ultrasound",
    "Breast MRI",
    "Breast PET Scan",
    "Breast CT Scan",
    "Breast Biopsy",
    "Breast Thermography",
    "Breast Cancer Screening",
    "Breast Cancer Diagnosis",
    "Breast Cancer Staging",
    "Breast Cancer Monitoring",
    "Breast Cancer Surveillance",
    "Breast Cancer Treatment Response Assessment",
    "Breast Cancer Recurrence Monitoring",
    "Breast Lesion Localization",
    "Breast Tumor Localization",
    "Breast Lumpectomy Localization",
    "Breast Cancer Localization",
    "Breast Tumor Excision Localization",
    "Breast Cancer Surgery Planning",
    "Breast Cancer Radiation Therapy Planning",
    "Breast Cancer Chemotherapy Planning",
    "Breast Cancer Immunotherapy Planning",
    "Breast Cancer Hormone Therapy Planning",
    "Breast Cancer Targeted Therapy Planning",
    "Breast Cancer Palliative Care Planning",
    "Breast Cancer Supportive Care Planning",
    "Breast Cancer Survivorship Care Planning",
    "Breast Cancer Rehabilitation Planning",
    "Breast Cancer Genetic Testing Planning",
    "Breast Cancer Counseling",
    "Breast Cancer Education",
    "Breast Cancer Risk Assessment",
    "Breast Cancer Prevention Counseling",
    "Breast Cancer Screening Counseling",
    "Breast Cancer Diagnostic Counseling",
    "Breast Cancer Staging Counseling",
    "Breast Cancer Treatment Counseling",
    "Breast Cancer Survivorship Counseling",
    "Breast Cancer Palliative Care Counseling",
    "Breast Cancer Supportive Care Counseling",
    "Breast Cancer Rehabilitation Counseling",
    "Breast Cancer Genetic Testing Counseling",
    "Breast Cancer Surgery Counseling",
    "Breast Cancer Radiation Therapy Counseling",
    "Breast Cancer Chemotherapy Counseling",
    "Breast Cancer Immunotherapy Counseling",
    "Breast Cancer Hormone Therapy Counseling",
    "Breast Cancer Targeted Therapy Counseling",
    "Breast Cancer Rehabilitation Counseling",
    "Breast Cancer Genetic Testing Counseling",
    "Breast Cancer Second Opinion Counseling",
    "Breast Cancer Clinical Trial Counseling",
    "Breast Cancer Palliative Care Counseling",
    "Breast Cancer Supportive Care Counseling",
    "Breast Cancer Survivorship Counseling",
    "Breast Cancer Rehabilitation Counseling",
    "Breast Cancer Genetic Testing Counseling",
    "Breast Cancer Prevention",
    "Breast Cancer Screening",
    "Breast Cancer Diagnosis",
    "Breast Cancer Staging",
    "Breast Cancer Monitoring",
    "Breast Cancer Surveillance",
    "Breast Cancer Treatment Response Assessment",
    "Breast Cancer Recurrence Monitoring",
    "Breast Cancer Metastasis Monitoring",
    "Breast Lesion Localization",
    "Breast Tumor Localization",
    "Breast Lumpectomy Localization",
]

# blood_test_names.py

# List of blood test names
blood_test_names = [
    "Complete Blood Count (CBC)",
    "Basic Metabolic Panel (BMP)",
    "Comprehensive Metabolic Panel (CMP)",
    "Liver Function Tests (LFTs)",
    "Renal Function Panel",
    "Lipid Panel",
    "Thyroid Stimulating Hormone (TSH)",
    "Hemoglobin A1c (HbA1c)",
    "C-Reactive Protein (CRP)",
    "Prothrombin Time (PT)",
    "Activated Partial Thromboplastin Time (aPTT)",
    "Blood Glucose",
    "Serum Electrolytes (Sodium, Potassium, Chloride)",
    "Blood Urea Nitrogen (BUN)",
    "Creatinine",
    "Albumin",
    "Bilirubin",
    "Hematocrit",
    "Platelet Count",
    "White Blood Cell Count (WBC)",
    "Red Blood Cell Count (RBC)",
    "Mean Corpuscular Volume (MCV)",
    "Mean Corpuscular Hemoglobin (MCH)",
    "Mean Corpuscular Hemoglobin Concentration (MCHC)",
    "Red Cell Distribution Width (RDW)",
    "Neutrophils",
    "Lymphocytes",
    "Monocytes",
    "Eosinophils",
    "Basophils",
    "Immature Granulocytes",
    "Glucose Tolerance Test (GTT)",
    "Glycated Albumin (GA)",
    "Insulin Level",
    "Lactate Dehydrogenase (LDH)",
    "Creatine Kinase (CK)",
    "Troponin",
    "Brain Natriuretic Peptide (BNP)",
    "Procalcitonin",
    "Ferritin",
    "Vitamin D",
    "Folate",
    "Vitamin B12",
    "Iron",
    "Total Iron Binding Capacity (TIBC)",
    "Ferritin",
    "Transferrin",
    "Thyroxine (T4)",
    "Triiodothyronine (T3)",
    "Free Thyroxine Index (FTI)",
    "Thyroid Peroxidase Antibody (TPOAb)",
    "Thyroglobulin Antibody (TgAb)",
    "Antithyroglobulin Antibody",
    "Antithyroid Microsomal Antibodies",
    "Thyroid-Stimulating Immunoglobulin (TSI)",
    "Parathyroid Hormone (PTH)",
    "Calcium",
    "Ionized Calcium",
    "Magnesium",
    "Phosphorus",
    "Uric Acid",
    "Cortisol",
    "Testosterone",
    "Estradiol",
    "Progesterone",
    "Follicle-Stimulating Hormone (FSH)",
    "Luteinizing Hormone (LH)",
    "Prolactin",
    "Dehydroepiandrosterone (DHEA)",
    "Dehydroepiandrosterone Sulfate (DHEA-S)",
    "Androstenedione",
    "17-Hydroxyprogesterone",
    "Catecholamines",
    "Serotonin",
    "Catecholamine Metabolites (Vanillylmandelic Acid, Metanephrines, Normetanephrine, Metadrenaline)",
    "Insulin-like Growth Factor 1 (IGF-1)",
    "Insulin-like Growth Factor Binding Protein 3 (IGFBP-3)",
    "Acid Phosphatase",
    "Prostate-Specific Antigen (PSA)",
    "Alkaline Phosphatase (ALP)",
    "Gamma-Glutamyl Transferase (GGT)",
    "Alanine Aminotransferase (ALT)",
    "Aspartate Aminotransferase (AST)",
    "Total Protein",
    "Albumin",
    "Globulin",
    "Total Bilirubin",
    "Direct Bilirubin",
    "Indirect Bilirubin",
    "Ammonia",
    "Total Cholesterol",
    "High-Density Lipoprotein (HDL) Cholesterol",
    "Low-Density Lipoprotein (LDL) Cholesterol",
    "Very Low-Density Lipoprotein (VLDL) Cholesterol",
    "Triglycerides",
    "Creatine Kinase MB (CK-MB)",
    "Troponin I",
    "Troponin T",
    "Myoglobin",
    "Lactate",
    "pH",
    "Partial Pressure of Carbon Dioxide (pCO2)",
    "Partial Pressure of Oxygen (pO2)",
    "Oxygen Saturation (SaO2)",
    "Bicarbonate (HCO3)",
    "Base Excess (BE)",
    "Anion Gap",
    "Arterial Blood Gas (ABG)",
    "Venous Blood Gas (VBG)",
    "Carbon Dioxide Content (CO2CT)",
    "Oxygen Content (O2CT)",
    "Total Hemoglobin",
    "Oxyhemoglobin",
    "Deoxyhemoglobin",
    "Methemoglobin",
    "Carboxyhemoglobin",
    "Methemoglobinemia",
    "Hemoglobin Variants",
    "Fetal Hemoglobin (HbF)",
    "Hemoglobin S (HbS)",
    "Hemoglobin C (HbC)",
    "Hemoglobin A2 (HbA2)",
    "Hemoglobin F (HbF)",
    "Erythrocyte Sedimentation Rate (ESR)",
    "Sickle Cell Test",
    "Coomb's Test",
    "Direct Coomb's Test",
    "Indirect Coomb's Test",
    "Kleihauer-Betke Test",
    "Haptoglobin",
    "Fibrinogen",
    "D-Dimer",
    "Factor Assays (Factors II, V, VII, VIII, IX, X, XI, XII)",
    "Protein C",
    "Protein S",
    "Antithrombin III",
    "Plasminogen",
    "Plasminogen Activator Inhibitor-1 (PAI-1)",
    "Tissue Plasminogen Activator (tPA)",
    "von Willebrand Factor (vWF)",
    "Platelet Aggregation Test",
    "PFA-100",
    "Bleeding Time",
    "Clot Retraction Time",
    "Coagulation Factor Activity Assays",
    "Activated Clotting Time (ACT)",
    "Thromboelastography (TEG)",
    "Activated Clotting Time (ACT)",
    "Clotting Time",
    "Thrombin Time",
    "Fibrinogen Activity",
    "Fibrinogen Antigen",
    "Fibrinogen Degradation Products (FDPs)",
    "Fibrin Monomer",
    "Fibrin Split Products (FSPs)",
    "Fibrin Degradation Fragment (FDF)",
    "Fibrin Degradation Products (FDPs)",
    "Fibrin Split Products (FSPs)",
    "Fibrin Degradation Fragment (FDF)",
    "Fibrinopeptide A (FPA)",
    "Fibrinopeptide B (FPB)",
    "Plasmin-α2-Antiplasmin Complex (PAP)",
    "Plasminogen Activator Inhibitor-1 (PAI-1)",
    "Tissue Plasminogen Activator (tPA)",
    "von Willebrand Factor (vWF)",
    "Platelet Aggregation Test",
    "PFA-100",
    "Bleeding Time",
    "Clot Retraction Time",
    "Coagulation Factor Activity Assays",
    "Activated Clotting Time (ACT)",
    "Thromboelastography (TEG)",
    "Activated Clotting Time (ACT)",
    "Clotting Time",
    "Thrombin Time",
    "Fibrinogen Activity",
    "Fibrinogen Antigen",
    "Fibrinogen Degradation Products (FDPs)",
    "Fibrin Monomer",
    "Fibrin Split Products (FSPs)",
    "Fibrin Degradation Fragment (FDF)",
    "Fibrin Degradation Products (FDPs)",
    "Fibrin Split Products (FSPs)",
    "Fibrin Degradation Fragment (FDF)",
    "Fibrinopeptide A (FPA)",
    "Fibrinopeptide B (FPB)",
    "Plasmin-α2-Antiplasmin Complex (PAP)",
    "Plasminogen Activator Inhibitor-1 (PAI-1)",
    "Tissue Plasminogen Activator (tPA)",
    "von Willebrand Factor (vWF)",
    "Platelet Aggregation Test",
    "PFA-100",
    "Bleeding Time",
    "Clot Retraction Time",
    "Coagulation Factor Activity Assays",
    "Activated Clotting Time (ACT)",
    "Thromboelastography (TEG)",
    "Activated Clotting Time (ACT)",
    "Clotting Time",
    "Thrombin Time",
    "Fibrinogen Activity",
    "Fibrinogen Antigen",
    "Fibrinogen Degradation Products (FDPs)",
    "Fibrin Monomer",
    "Fibrin Split Products (FSPs)",
    "Fibrin Degradation Fragment (FDF)",
    "Fibrin Degradation Products (FDPs)",
    "Fibrin Split Products (FSPs)",
    "Fibrin Degradation Fragment (FDF)",
    "Fibrinopeptide A (FPA)",
    "Fibrinopeptide B (FPB)",
    "Plasmin-α2-Antiplasmin Complex (PAP)",
    "Plasminogen Activator Inhibitor-1 (PAI-1)",
    "Tissue Plasminogen Activator (tPA)",
    "von Willebrand Factor (vWF)",
    "Platelet Aggregation Test",
    "PFA-100",
    "Bleeding Time",
    "Clot Retraction Time",
    "Coagulation Factor Activity Assays",
    "Activated Clotting Time (ACT)",
    "Thromboelastography (TEG)",
    "Activated Clotting Time (ACT)",
    "Clotting Time",
    "Thrombin Time",
    "Fibrinogen Activity",
    "Fibrinogen Antigen",
    "Fibrinogen Degradation Products (FDPs)",
    "Fibrin Monomer",
    "Fibrin Split Products (FSPs)",
    "Fibrin Degradation Fragment (FDF)",
    "Fibrin Degradation Products (FDPs)",
    "Fibrin Split Products (FSPs)",
    "Fibrin Degradation Fragment (FDF)",
    "Fibrinopeptide A (FPA)",
    "Fibrinopeptide B (FPB)",
    "Plasmin-α2-Antiplasmin Complex (PAP)",
    "Plasminogen Activator Inhibitor-1 (PAI-1)",
    "Tissue Plasminogen Activator (tPA)",
    "von Willebrand Factor (vWF)",
    "Platelet Aggregation Test",
    "PFA-100",
    "Bleeding Time",
    "Clot Retraction Time",
    "Coagulation Factor Activity Assays",
    "Activated Clotting Time (ACT)",
    "Thromboelastography (TEG)",
    "Activated Clotting Time (ACT)",
    "Clotting Time",
    "Thrombin Time",
    "Fibrinogen Activity",
    "Fibrinogen Antigen",
    "Fibrinogen Degradation Products (FDPs)",
    "Fibrin Monomer",
    "Fibrin Split Products (FSPs)",
    "Fibrin Degradation Fragment (FDF)",
    "Fibrin Degradation Products (FDPs)",
    "Fibrin Split Products (FSPs)",
    "Fibrin Degradation Fragment (FDF)",
    "Fibrinopeptide A (FPA)",
    "Fibrinopeptide B (FPB)",
    "Plasmin-α2-Antiplasmin Complex (PAP)",
    "Plasminogen Activator Inhibitor-1 (PAI-1)",
    "Tissue Plasminogen Activator (tPA)",
    "von Willebrand Factor (vWF)",
    "Platelet Aggregation Test",
    "PFA-100",
    "Bleeding Time",
    "Clot Retraction Time",
    "Coagulation Factor Activity Assays",
    "Activated Clotting Time (ACT)",
    "Thromboelastography (TEG)",
]


# ethnicity_list.py

# List of ethnicities and nationalities
ethnicity_list = [
    "African British",
    "Asian",
    "White",
    "Hispanic",
    "Latino",
    "Arab",
    "Native British",
    "Pacific Islander",
    "Aboriginal",
    "Caucasian",
    "European",
    "Middle Eastern",
    "Indian",
    "Chinese",
    "Japanese",
    "Korean",
    "Vietnamese",
    "Filipino",
    "Thai",
    "Indonesian",
    "Malaysian",
    "Singaporean",
    "Burmese",
    "Laotian",
    "Cambodian",
    "Taiwanese",
    "Pakistani",
    "Bangladeshi",
    "Sri Lankan",
    "Nepali",
    "Bhutanese",
    "Tibetan",
    "Afghan",
    "Iranian",
    "Iraqi",
    "Syrian",
    "Lebanese",
    "Jordanian",
    "Palestinian",
    "Israeli",
    "Turkish",
    "Greek",
    "Italian",
    "French",
    "German",
    "British",
    "Irish",
    "Scottish",
    "Welsh",
    "Russian",
    "Polish",
    "Swedish",
    "Norwegian",
    "Finnish",
    "Danish",
    "Dutch",
    "Portuguese",
    "Spanish",
    "Mexican",
    "Brazilian",
    "Argentinian",
    "Chilean",
    "Peruvian",
    "Colombian",
    "Venezuelan",
    "Ecuadorian",
    "Bolivian",
    "Uruguayan",
    "Paraguayan",
    "Cuban",
    "Puerto Rican",
    "Dominican",
    "Salvadoran",
    "Guatemalan",
    "Honduran",
    "Nicaraguan",
    "Costa Rican",
    "Panamanian",
    "Canadian",
    "British",
    "Australian",
    "New Zealander",
    "Fijian",
    "Tongan",
    "Samoan",
    "Marshallese",
    "Palauan",
    "Micronesian",
    "Papua New Guinean",
    "Solomon Islander",
    "Vanuatuan",
    "Maori",
    "Icelander",
    "Greenlander",
    "Albanian",
    "Bosnian",
    "Serbian",
    "Croatian",
    "Macedonian",
    "Kosovar",
    "Montenegrin",
    "Georgian",
    "Armenian",
    "Azerbaijani",
    "Kazakh",
    "Uzbek",
    "Turkmen",
    "Kyrgyz",
    "Tajik",
    "Mongolian",
    "Tuvan",
    "Siberian",
    "Uighur",
    "Tatar",
    "Chechen",
    "Yakut",
    "Chukchi",
    "Inuit",
    "Sami",
    "Basque",
    "Catalan",
    "Galician",
    "Quechua",
    "Mayan",
    "Aztec",
    "Incan",
    "Mapuche",
    "Maasai",
    "Zulu",
    "Xhosa",
    "Swazi",
    "Sotho",
    "Tswana",
    "Ndebele",
    "Shona",
    "Khoisan",
    "Hutu",
    "Tutsi",
    "Bantu",
    "Afrikaner",
    "Boer",
    "Coloured",
    "Cajun",
    "Creole",
    "Gullah",
    "Garifuna",
    "Jamaican",
    "Haitian",
    "Trinidadian",
    "Grenadian",
    "Bajan",
    "Lucian",
    "Dominican (Republic)",
    "Antiguan",
    "Barbudan",
    "Kittian",
    "Vincentian",
    "Guyanese",
    "Surinamese",
    "Trinidadian",
    "Tobagonian",
    "Bahamian",
    "Caymanian",
    "Bermudian",
    "British Virgin Islander",
    "Turks and Caicos Islander",
    "Puerto Rican",
    "Mexican British",
    "Cuban British",
    "Dominican British",
    "Salvadoran British",
    "Guatemalan British",
    "Honduran British",
    "Nicaraguan British",
    "Costa Rican British",
    "Panamanian British",
    "Colombian British",
    "Venezuelan British",
    "Ecuadorian British",
    "Peruvian British",
    "Chilean British",
    "Argentinian British",
    "Brazilian British",
    "Uruguayan British",
    "Paraguayan British",
    "Bolivian British",
    "British British",
    "Irish British",
    "Italian British",
    "German British",
    "French British",
    "Dutch British",
    "Polish British",
    "Swedish British",
    "Norwegian British",
    "Finnish British",
    "Danish British",
    "Portuguese British",
    "Greek British",
    "Russian British",
    "Armenian British",
    "Albanian British",
    "Bosnian British",
    "Serbian British",
    "Croatian British",
    "Macedonian British",
    "Kosovar British",
    "Montenegrin British",
    "Ukrainian British",
    "Belarusian British",
    "Latvian British",
    "Lithuanian British",
    "Estonian British",
    "Czech British",
    "Slovak British",
    "Hungarian British",
    "Romanian British",
    "Bulgarian British",
    "Moldovan British",
    "Georgian British",
    "Azerbaijani British",
    "Kazakh British",
    "Turkmen British",
    "Uzbek British",
    "Kyrgyz British",
    "Tajik British",
    "Afghan British",
    "Iranian British",
    "Iraqi British",
    "Syrian British",
    "Lebanese British",
    "Jordanian British",
    "Palestinian British",
    "Israeli British",
    "Turkish British",
    "Arab British",
    "Egyptian British",
    "Algerian British",
    "Tunisian British",
    "Moroccan British",
    "Libyan British",
    "Sudanese British",
    "Somali British",
    "Eritrean British",
    "Djiboutian British",
    "Yemeni British",
    "Omani British",
    "Qatari British",
    "Bahraini British",
    "Kuwaiti British",
    "Emirati British",
    "Saudi British",
    "Syrian British",
    "Jordanian British",
    "Palestinian British",
    "Israeli British",
    "Lebanese British",
    "Iraqi British",
    "Egyptian British",
    "Saudi British",
    "Yemeni British",
    "Emirati British",
    "Qatari British",
    "Kuwaiti British",
    "Bahraini British",
    "Omani British",
    "Tunisian British",
    "Moroccan British",
    "Algerian British",
    "Libyan British",
    "Sudanese British",
    "Somali British",
    "Eritrean British",
    "Djiboutian British",
    "Comoran British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Sahrawi British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Djiboutian British",
    "Eritrean British",
    "Somali British",
    "Ethiopian British",
    "Ugandan British",
    "Rwandan British",
    "Burundian British",
    "Kenyan British",
    "South Sudanese British",
    "Sudanese British",
    "South Sudanese British",
    "Sudanese British",
    "Ethiopian British",
    "Eritrean British",
    "Djiboutian British",
    "Somali British",
    "Ugandan British",
    "Rwandan British",
    "Burundian British",
    "Kenyan British",
    "South Sudanese British",
    "Sudanese British",
    "South Sudanese British",
    "Sudanese British",
    "Ethiopian British",
    "Eritrean British",
    "Djiboutian British",
    "Somali British",
    "Ugandan British",
    "Rwandan British",
    "Burundian British",
    "Kenyan British",
    "South Sudanese British",
    "Sudanese British",
    "South Sudanese British",
    "Sudanese British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Lesotho British",
    "Moroccan British",
    "Algerian British",
    "Tunisian British",
    "Libyan British",
    "Egyptian British",
    "Sudanese British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Lesotho British",
    "Moroccan British",
    "Algerian British",
    "Tunisian British",
    "Libyan British",
    "Egyptian British",
    "Sudanese British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Sahrawi British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Lesotho British",
    "Moroccan British",
    "Algerian British",
    "Tunisian British",
    "Libyan British",
    "Egyptian British",
    "Sudanese British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Sahrawi British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Lesotho British",
    "Moroccan British",
    "Algerian British",
    "Tunisian British",
    "Libyan British",
    "Egyptian British",
    "Sudanese British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Sahrawi British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Lesotho British",
    "Moroccan British",
    "Algerian British",
    "Tunisian British",
    "Libyan British",
    "Egyptian British",
    "Sudanese British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Sahrawi British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Lesotho British",
    "Moroccan British",
    "Algerian British",
    "Tunisian British",
    "Libyan British",
    "Egyptian British",
    "Sudanese British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Sahrawi British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Lesotho British",
    "Moroccan British",
    "Algerian British",
    "Tunisian British",
    "Libyan British",
    "Egyptian British",
    "Sudanese British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Sahrawi British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Lesotho British",
    "Moroccan British",
    "Algerian British",
    "Tunisian British",
    "Libyan British",
    "Egyptian British",
    "Sudanese British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Sahrawi British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Lesotho British",
    "Moroccan British",
    "Algerian British",
    "Tunisian British",
    "Libyan British",
    "Egyptian British",
    "Sudanese British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Sahrawi British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Lesotho British",
    "Moroccan British",
    "Algerian British",
    "Tunisian British",
    "Libyan British",
    "Egyptian British",
    "Sudanese British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Sahrawi British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Lesotho British",
    "Moroccan British",
    "Algerian British",
    "Tunisian British",
    "Libyan British",
    "Egyptian British",
    "Sudanese British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Sahrawi British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Lesotho British",
    "Moroccan British",
    "Algerian British",
    "Tunisian British",
    "Libyan British",
    "Egyptian British",
    "Sudanese British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Sahrawi British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Lesotho British",
    "Moroccan British",
    "Algerian British",
    "Tunisian British",
    "Libyan British",
    "Egyptian British",
    "Sudanese British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Sahrawi British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Lesotho British",
    "Moroccan British",
    "Algerian British",
    "Tunisian British",
    "Libyan British",
    "Egyptian British",
    "Sudanese British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Sahrawi British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Lesotho British",
    "Moroccan British",
    "Algerian British",
    "Tunisian British",
    "Libyan British",
    "Egyptian British",
    "Sudanese British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Sahrawi British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Lesotho British",
    "Moroccan British",
    "Algerian British",
    "Tunisian British",
    "Libyan British",
    "Egyptian British",
    "Sudanese British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Sahrawi British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
    "Zimbabwean British",
    "Namibian British",
    "Botswana British",
    "Swazi British",
    "South African British",
    "Lesotho British",
    "Moroccan British",
    "Algerian British",
    "Tunisian British",
    "Libyan British",
    "Egyptian British",
    "Sudanese British",
    "Mauritanian British",
    "Malian British",
    "Nigerien British",
    "Chadian British",
    "Sahrawi British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Togolese British",
    "Beninese British",
    "Ivorian British",
    "Burkinabe British",
    "Ghanaian British",
    "Nigerian British",
    "Cameroonian British",
    "Equatorial Guinean British",
    "Gabonese British",
    "Congolese British",
    "Central African British",
    "Sao Tomean British",
    "Angolan British",
    "Zambian British",
    "Malawian British",
    "Tanzanian British",
    "Seychellois British",
    "Mauritian British",
    "Malagasy British",
    "Comoran British",
    "Mozambican British",
]
