"""
pat2vec: A package for processing patient data.

This file is auto-generated by `generate_init.py`.
It exposes the main functions and methods of the pat2vec library for easy access.
"""

from .main_pat2vec import (
    main
)
from .pat2vec_get_methods.get_method_appointments import (
    get_appointments
)
from .pat2vec_get_methods.get_method_bed import (
    get_bed
)
from .pat2vec_get_methods.get_method_bloods import (
    get_current_pat_bloods
)
from .pat2vec_get_methods.get_method_bmi import (
    get_bmi_features
)
from .pat2vec_get_methods.get_method_core02 import (
    get_core_02
)
from .pat2vec_get_methods.get_method_core_resus import (
    get_core_resus
)
from .pat2vec_get_methods.get_method_current_pat_annotations_mrc_cs import (
    get_current_pat_annotations_mrc_cs
)
from .pat2vec_get_methods.get_method_demo import (
    get_demographics3
)
from .pat2vec_get_methods.get_method_demographics import (
    get_demo, get_demographics3_batch
)
from .pat2vec_get_methods.get_method_diagnostics import (
    get_current_pat_diagnostics
)
from .pat2vec_get_methods.get_method_drugs import (
    get_current_pat_drugs
)
from .pat2vec_get_methods.get_method_hosp_site import (
    get_hosp_site
)
from .pat2vec_get_methods.get_method_news import (
    get_news
)
from .pat2vec_get_methods.get_method_pat_annotations import (
    get_current_pat_annotations
)
from .pat2vec_get_methods.get_method_report_annotations import (
    get_current_pat_report_annotations
)
from .pat2vec_get_methods.get_method_smoking import (
    get_smoking
)
from .pat2vec_get_methods.get_method_textual_obs_annotations import (
    get_current_pat_textual_obs_annotations
)
from .pat2vec_get_methods.get_method_vte_status import (
    get_vte_status
)
from .pat2vec_main_methods.main_batch import (
    main_batch
)
from .pat2vec_pat_list.get_patient_treatment_list import (
    analyze_client_codes, extract_treatment_id_list_from_docs, generate_control_list,
    get_all_patients_list, sanitize_hospital_ids
)
from .patvec_get_batch_methods.get_merged_batches import (
    get_merged_pat_batch_appointments, get_merged_pat_batch_bloods,
    get_merged_pat_batch_bmi, get_merged_pat_batch_demo,
    get_merged_pat_batch_diagnostics, get_merged_pat_batch_drugs,
    get_merged_pat_batch_epr_docs, get_merged_pat_batch_mct_docs,
    get_merged_pat_batch_news, get_merged_pat_batch_obs, get_merged_pat_batch_reports,
    get_merged_pat_batch_textual_obs_docs, save_group, split_and_save_csv,
    verify_split_data_concatenated, verify_split_data_individual
)
from .patvec_get_batch_methods.get_prefetch_batches import (
    BatchConfig, prefetch_batches
)
from .patvec_get_batch_methods.main import (
    get_pat_batch_appointments, get_pat_batch_bloods, get_pat_batch_bmi,
    get_pat_batch_demo, get_pat_batch_diagnostics, get_pat_batch_drugs,
    get_pat_batch_epr_docs, get_pat_batch_epr_docs_annotations, get_pat_batch_mct_docs,
    get_pat_batch_mct_docs_annotations, get_pat_batch_news, get_pat_batch_obs,
    get_pat_batch_reports, get_pat_batch_reports_docs_annotations,
    get_pat_batch_textual_obs_annotations, get_pat_batch_textual_obs_docs
)
from .tests.test_methods_get import (
    TestFilterDataFrameByTimestamp
)
from .util.anonymisation_data_methods import (
    anonymize_feature_names, deanonymize_feature_names
)
from .util.clinical_note_splitter import (
    find_date, split_and_append_chunks, split_clinical_notes, split_clinical_notes_mct
)
from .util.cogstack_v8_lite import (
    CogStack, appendAge, appendAgeAtRecord, append_age_at_record_series,
    bulk_str_extract, bulk_str_extract_round_robin, bulk_str_findall, catch,
    cohort_searcher_no_terms, cohort_searcher_no_terms_fuzzy,
    cohort_searcher_with_terms_and_search, cohort_searcher_with_terms_and_search_multi,
    cohort_searcher_with_terms_no_search, create_credentials_file, dataframe_generator,
    date_cleaner, df_column_uniquify, find_date, get_demographics, get_demographics2,
    iterative_multi_term_cohort_searcher_no_terms_fuzzy,
    iterative_multi_term_cohort_searcher_no_terms_fuzzy_mct,
    iterative_multi_term_cohort_searcher_no_terms_fuzzy_textual_obs, list_chunker,
    matcher, nearest, pull_and_write, pylist2searchlist, set_index_safe_wrapper,
    split_clinical_notes, stringlist2pylist, stringlist2searchlist, without_keys
)
from .util.compile_requirements import (
    append_to_file, process_requirements, run_pip_compile
)
from .util.config_pat2vec import (
    MultiStream, calculate_interval, config_class, get_test_options_dict,
    swap_start_end, update_global_start_date
)
from .util.current_pat_batch_path_methods import (
    PathsClass
)
from .util.elasticsearch_methods import (
    get_guess_datetime_column, guess_datetime_columns, handle_inconsistent_dtypes,
    ingest_data_to_elasticsearch
)
from .util.ethnicity_abstractor import (
    EthnicityAbstractor
)
from .util.evaluation_methods import (
    CsvProfiler, compare_ipw_annotation_rows
)
from .util.evaluation_methods_ploting import (
    generate_pie_charts
)
from .util.filter_methods import (
    apply_bloods_data_type_filter, apply_data_type_epr_docs_filters,
    apply_data_type_mct_docs_filters, filter_dataframe_by_fuzzy_terms
)
from .util.get_dummy_data_cohort_searcher import (
    cohort_searcher_with_terms_and_search_dummy, dummy_CAT,
    dummy_medcat_annotation_generator, extract_date_range,
    extract_search_term_obscatalogmasteritem_displayname, generate_appointments_data,
    generate_basic_observations_data, generate_basic_observations_textual_obs_data,
    generate_diagnostic_orders_data, generate_drug_orders_data,
    generate_epr_documents_data, generate_epr_documents_personal_data,
    generate_observations_MRC_text_data, generate_observations_Reports_text_data,
    generate_observations_data, generate_patient_timeline,
    generate_patient_timeline_faker, generate_uuid, generate_uuid_list,
    get_patient_timeline_dummy, maybe_nan, random_sample,
    run_generate_patient_timeline_and_append
)
from .util.helper_functions import (
    extract_nhs_numbers, get_search_client_idcode_list_from_nhs_number_list
)
from .util.logger_setup import (
    setup_logger
)
from .util.medcat_misc_methods import (
    create_ner_results_dataframe, extract_labels_from_medcat_annotation_export,
    manually_label_annotation_df, medcat_trainer_export_to_df,
    parse_medcat_trainer_project_json, plot_ner_results, recreate_json
)
from .util.methods_annotation import (
    annot_pat_batch_docs, calculate_pretty_name_count_features,
    check_pat_document_annotation_complete, filter_annot_dataframe,
    get_pat_batch_textual_obs_annotation_batch, get_pat_document_annotation_batch,
    get_pat_document_annotation_batch_mct, get_pat_document_annotation_batch_reports,
    json_to_dataframe, multi_annots_to_df, multi_annots_to_df_mct,
    multi_annots_to_df_reports, multi_annots_to_df_textual_obs, parse_meta_anns
)
from .util.methods_annotation_regex import (
    append_regex_term_counts
)
from .util.methods_get import (
    add_offset_column, build_patient_dict, check_sftp_connection, convert_date,
    convert_date, convert_timestamp_to_tuple, create_folders,
    create_folders_annot_csv_wrapper, create_folders_for_pat, create_local_folders,
    create_remote_folders, dump_results, enum_exact_target_date_vector,
    enum_target_date_vector, exist_check, filter_dataframe_by_timestamp,
    filter_stripped_list, generate_date_list, get_empty_date_vector, get_free_gpu,
    get_start_end_year_month, list_dir_wrapper, list_dir_wrapper, list_dir_wrapper,
    method1, method1, method2, method2, read_csv_wrapper, read_remote, sftp_exists,
    test_datetime_formats, update_pbar, write_csv_wrapper, write_remote
)
from .util.methods_get_medcat import (
    get_cat
)
from .util.methods_post_get import (
    check_csv_files_in_directory, check_csv_integrity,
    copy_project_folders_with_substring_match, retrieve_pat_annotations
)
from .util.post_processing import (
    aggregate_dataframe_mean, build_ipw_dataframe, check_list_presence,
    collapse_df_to_mean, convert_true_to_float, copy_files_and_dirs, count_files,
    drop_columns_with_all_nan, extract_datetime_from_binary_columns,
    extract_datetime_from_binary_columns_chunk_reader, extract_datetime_to_column,
    extract_types_from_csv, filter_and_select_rows, filter_and_update_csv,
    filter_annot_dataframe2, filter_dataframe_by_cui, filter_dataframe_n_lists,
    get_all_target_annots, get_pat_ipw_record, impute_dataframe, impute_datetime,
    join_icd10_OPC4S_codes_to_annot, join_icd10_codes_to_annot, missing_percentage_df,
    plot_missing_pattern_bloods, process_chunk, process_csv_files,
    process_csv_files_multi, produce_filtered_annotation_dataframe,
    remove_file_from_paths, retrieve_pat_annots_mct_epr, save_missing_values_pickle
)
from .util.post_processing_build_methods import (
    build_merged_bloods, build_merged_epr_mct_annot_df, build_merged_epr_mct_doc_df,
    filter_annot_dataframe, get_annots_joined_to_docs, join_docs_to_annots,
    merge_appointments_csv, merge_bmi_csv, merge_demographics_csv,
    merge_diagnostics_csv, merge_drugs_csv, merge_news_csv, retrieve_pat_bloods,
    retrieve_pat_docs_mct_epr
)
from .util.post_processing_medcat import (
    coerce_document_df_to_medcat_trainer_input, sample_by_terms
)
from .util.pre_get_drug_treatment_docs import (
    get_treatment_records_by_drug_order_name, iterative_drug_treatment_search
)
from .util.pre_processing import (
    calculate_age_append, demo_to_latest, draw_document_samples,
    get_treatment_docs_by_iterative_multi_term_cohort_searcher_no_terms_fuzzy,
    search_cohort
)
from .util.presentation_methods import (
    create_powerpoint_from_images, create_powerpoint_from_images_group,
    create_powerpoint_slides, create_powerpoint_slides_client_idcode_groups,
    group_images_by_suffix
)


# Define the public API of the package
__all__ = [
    "BatchConfig", "CogStack", "CsvProfiler", "EthnicityAbstractor", "MultiStream",
    "PathsClass", "TestFilterDataFrameByTimestamp", "add_offset_column",
    "aggregate_dataframe_mean", "analyze_client_codes", "annot_pat_batch_docs",
    "anonymize_feature_names", "appendAge", "appendAgeAtRecord",
    "append_age_at_record_series", "append_regex_term_counts", "append_to_file",
    "apply_bloods_data_type_filter", "apply_data_type_epr_docs_filters",
    "apply_data_type_mct_docs_filters", "build_ipw_dataframe", "build_merged_bloods",
    "build_merged_epr_mct_annot_df", "build_merged_epr_mct_doc_df",
    "build_patient_dict", "bulk_str_extract", "bulk_str_extract_round_robin",
    "bulk_str_findall", "calculate_age_append", "calculate_interval",
    "calculate_pretty_name_count_features", "catch", "check_csv_files_in_directory",
    "check_csv_integrity", "check_list_presence",
    "check_pat_document_annotation_complete", "check_sftp_connection",
    "coerce_document_df_to_medcat_trainer_input", "cohort_searcher_no_terms",
    "cohort_searcher_no_terms_fuzzy", "cohort_searcher_with_terms_and_search",
    "cohort_searcher_with_terms_and_search_dummy",
    "cohort_searcher_with_terms_and_search_multi",
    "cohort_searcher_with_terms_no_search", "collapse_df_to_mean",
    "compare_ipw_annotation_rows", "config_class", "convert_date",
    "convert_timestamp_to_tuple", "convert_true_to_float", "copy_files_and_dirs",
    "copy_project_folders_with_substring_match", "count_files",
    "create_credentials_file", "create_folders", "create_folders_annot_csv_wrapper",
    "create_folders_for_pat", "create_local_folders", "create_ner_results_dataframe",
    "create_powerpoint_from_images", "create_powerpoint_from_images_group",
    "create_powerpoint_slides", "create_powerpoint_slides_client_idcode_groups",
    "create_remote_folders", "dataframe_generator", "date_cleaner",
    "deanonymize_feature_names", "demo_to_latest", "df_column_uniquify",
    "draw_document_samples", "drop_columns_with_all_nan", "dummy_CAT",
    "dummy_medcat_annotation_generator", "dump_results",
    "enum_exact_target_date_vector", "enum_target_date_vector", "exist_check",
    "extract_date_range", "extract_datetime_from_binary_columns",
    "extract_datetime_from_binary_columns_chunk_reader", "extract_datetime_to_column",
    "extract_labels_from_medcat_annotation_export", "extract_nhs_numbers",
    "extract_search_term_obscatalogmasteritem_displayname",
    "extract_treatment_id_list_from_docs", "extract_types_from_csv",
    "filter_and_select_rows", "filter_and_update_csv", "filter_annot_dataframe",
    "filter_annot_dataframe2", "filter_dataframe_by_cui",
    "filter_dataframe_by_fuzzy_terms", "filter_dataframe_by_timestamp",
    "filter_dataframe_n_lists", "filter_stripped_list", "find_date",
    "generate_appointments_data", "generate_basic_observations_data",
    "generate_basic_observations_textual_obs_data", "generate_control_list",
    "generate_date_list", "generate_diagnostic_orders_data",
    "generate_drug_orders_data", "generate_epr_documents_data",
    "generate_epr_documents_personal_data", "generate_observations_MRC_text_data",
    "generate_observations_Reports_text_data", "generate_observations_data",
    "generate_patient_timeline", "generate_patient_timeline_faker",
    "generate_pie_charts", "generate_uuid", "generate_uuid_list",
    "get_all_patients_list", "get_all_target_annots", "get_annots_joined_to_docs",
    "get_appointments", "get_bed", "get_bmi_features", "get_cat", "get_core_02",
    "get_core_resus", "get_current_pat_annotations",
    "get_current_pat_annotations_mrc_cs", "get_current_pat_bloods",
    "get_current_pat_diagnostics", "get_current_pat_drugs",
    "get_current_pat_report_annotations", "get_current_pat_textual_obs_annotations",
    "get_demo", "get_demographics", "get_demographics2", "get_demographics3",
    "get_demographics3_batch", "get_empty_date_vector", "get_free_gpu",
    "get_guess_datetime_column", "get_hosp_site", "get_merged_pat_batch_appointments",
    "get_merged_pat_batch_bloods", "get_merged_pat_batch_bmi",
    "get_merged_pat_batch_demo", "get_merged_pat_batch_diagnostics",
    "get_merged_pat_batch_drugs", "get_merged_pat_batch_epr_docs",
    "get_merged_pat_batch_mct_docs", "get_merged_pat_batch_news",
    "get_merged_pat_batch_obs", "get_merged_pat_batch_reports",
    "get_merged_pat_batch_textual_obs_docs", "get_news", "get_pat_batch_appointments",
    "get_pat_batch_bloods", "get_pat_batch_bmi", "get_pat_batch_demo",
    "get_pat_batch_diagnostics", "get_pat_batch_drugs", "get_pat_batch_epr_docs",
    "get_pat_batch_epr_docs_annotations", "get_pat_batch_mct_docs",
    "get_pat_batch_mct_docs_annotations", "get_pat_batch_news", "get_pat_batch_obs",
    "get_pat_batch_reports", "get_pat_batch_reports_docs_annotations",
    "get_pat_batch_textual_obs_annotation_batch",
    "get_pat_batch_textual_obs_annotations", "get_pat_batch_textual_obs_docs",
    "get_pat_document_annotation_batch", "get_pat_document_annotation_batch_mct",
    "get_pat_document_annotation_batch_reports", "get_pat_ipw_record",
    "get_patient_timeline_dummy", "get_search_client_idcode_list_from_nhs_number_list",
    "get_smoking", "get_start_end_year_month", "get_test_options_dict",
    "get_treatment_docs_by_iterative_multi_term_cohort_searcher_no_terms_fuzzy",
    "get_treatment_records_by_drug_order_name", "get_vte_status",
    "group_images_by_suffix", "guess_datetime_columns", "handle_inconsistent_dtypes",
    "impute_dataframe", "impute_datetime", "ingest_data_to_elasticsearch",
    "iterative_drug_treatment_search",
    "iterative_multi_term_cohort_searcher_no_terms_fuzzy",
    "iterative_multi_term_cohort_searcher_no_terms_fuzzy_mct",
    "iterative_multi_term_cohort_searcher_no_terms_fuzzy_textual_obs",
    "join_docs_to_annots", "join_icd10_OPC4S_codes_to_annot",
    "join_icd10_codes_to_annot", "json_to_dataframe", "list_chunker",
    "list_dir_wrapper", "main", "main_batch", "manually_label_annotation_df", "matcher",
    "maybe_nan", "medcat_trainer_export_to_df", "merge_appointments_csv",
    "merge_bmi_csv", "merge_demographics_csv", "merge_diagnostics_csv",
    "merge_drugs_csv", "merge_news_csv", "method1", "method2", "missing_percentage_df",
    "multi_annots_to_df", "multi_annots_to_df_mct", "multi_annots_to_df_reports",
    "multi_annots_to_df_textual_obs", "nearest", "parse_medcat_trainer_project_json",
    "parse_meta_anns", "plot_missing_pattern_bloods", "plot_ner_results",
    "prefetch_batches", "process_chunk", "process_csv_files", "process_csv_files_multi",
    "process_requirements", "produce_filtered_annotation_dataframe", "pull_and_write",
    "pylist2searchlist", "random_sample", "read_csv_wrapper", "read_remote",
    "recreate_json", "remove_file_from_paths", "retrieve_pat_annotations",
    "retrieve_pat_annots_mct_epr", "retrieve_pat_bloods", "retrieve_pat_docs_mct_epr",
    "run_generate_patient_timeline_and_append", "run_pip_compile", "sample_by_terms",
    "sanitize_hospital_ids", "save_group", "save_missing_values_pickle",
    "search_cohort", "set_index_safe_wrapper", "setup_logger", "sftp_exists",
    "split_and_append_chunks", "split_and_save_csv", "split_clinical_notes",
    "split_clinical_notes_mct", "stringlist2pylist", "stringlist2searchlist",
    "swap_start_end", "test_datetime_formats", "update_global_start_date",
    "update_pbar", "verify_split_data_concatenated", "verify_split_data_individual",
    "without_keys", "write_csv_wrapper", "write_remote"
]
