"""
pat2vec: A package for processing patient data.

This file is auto-generated by `generate_init.py`.

It exposes the main functions and methods of the pat2vec library for easy access.

"""

__version__ = "0.3.4"

from .main_pat2vec import (
    main,
)
from .pat2vec_get_methods.get_method_appointments import (
    APPOINTMENT_FIELDS,
    get_appointments,
    search_appointments,
)
from .pat2vec_get_methods.get_method_bed import (
    BED_FIELDS,
    get_bed,
    search_bed_data,
)
from .pat2vec_get_methods.get_method_bloods import (
    BLOODS_FIELDS,
    get_current_pat_bloods,
    search_bloods_data,
)
from .pat2vec_get_methods.get_method_bmi import (
    BMI_FIELDS,
    calculate_bmi_features,
    get_bmi_features,
    search_bmi_observations,
)
from .pat2vec_get_methods.get_method_core02 import (
    CORE_O2_FIELDS,
    calculate_core_o2_features,
    clean_observation_value,
    get_core_02,
    search_core_o2_observations,
)
from .pat2vec_get_methods.get_method_core_resus import (
    CORE_RESUS_FIELDS,
    calculate_core_resus_features,
    get_core_resus,
    search_core_resus_observations,
)
from .pat2vec_get_methods.get_method_covid import (
    COVID_FIELDS,
    SEARCH_TERM_ES,
    SEARCH_TERM_PLAIN,
    calculate_covid_features,
    get_covid,
    search_covid,
)
from .pat2vec_get_methods.get_method_current_pat_annotations_mrc_cs import (
    get_current_pat_annotations_mrc_cs,
)
from .pat2vec_get_methods.get_method_demo import (
    DEMOGRAPHICS_FIELDS,
    get_demographics3,
    get_demographics_data,
    process_demographics_data,
    search_demographics,
)
from .pat2vec_get_methods.get_method_demographics import (
    get_demo,
    get_demographics3_batch,
)
from .pat2vec_get_methods.get_method_diagnostics import (
    COLUMNS_TO_DROP,
    DIAGNOSTICS_FIELDS,
    calculate_diagnostic_features,
    create_diagnostic_features_dataframe,
    get_current_pat_diagnostics,
    prepare_diagnostic_datetime,
    search_diagnostic_orders,
)
from .pat2vec_get_methods.get_method_drugs import (
    DRUG_FIELDS,
    calculate_drug_features,
    create_drug_features_dataframe,
    get_current_pat_drugs,
    prepare_drug_datetime,
    search_drug_orders,
)
from .pat2vec_get_methods.get_method_epic_clinical_notes import (
    EPIC_CLINICAL_NOTES_FIELDS,
    get_epic_clinical_notes,
    search_epic_clinical_notes,
)
from .pat2vec_get_methods.get_method_epic_clinical_notes_appointments import (
    EPIC_CLINICAL_NOTES_APPOINTMENTS_FIELDS,
    get_epic_clinical_notes_appointments,
    search_epic_clinical_notes_appointments,
)
from .pat2vec_get_methods.get_method_epic_encounters import (
    EPIC_ENCOUNTER_FIELDS,
    get_epic_encounters,
    search_epic_encounters,
)
from .pat2vec_get_methods.get_method_epic_imaging_reports import (
    EPIC_IMAGING_REPORTS_FIELDS,
    get_epic_imaging_reports,
    search_epic_imaging_reports,
)
from .pat2vec_get_methods.get_method_epic_lab_results import (
    EPIC_LAB_RESULTS_FIELDS,
    get_epic_lab_results,
    search_epic_lab_results,
)
from .pat2vec_get_methods.get_method_epic_medical_history import (
    EPIC_MEDICAL_HISTORY_FIELDS,
    get_epic_medical_history,
    search_epic_medical_history,
)
from .pat2vec_get_methods.get_method_epic_orders import (
    EPIC_ORDERS_FIELDS,
    get_epic_orders,
    search_epic_orders,
)
from .pat2vec_get_methods.get_method_epic_orders_annotations import (
    get_current_pat_epic_orders_annotations,
)
from .pat2vec_get_methods.get_method_epic_patients import (
    EPIC_PATIENTS_FIELDS,
    get_epic_patients,
    search_epic_patients,
)
from .pat2vec_get_methods.get_method_hosp_site import (
    HOSP_SITE_FIELDS,
    SEARCH_TERM,
    calculate_hospital_site_features,
    get_hosp_site,
    prepare_hospital_site_data,
    search_hospital_site,
)
from .pat2vec_get_methods.get_method_news import (
    compute_feature_stats,
    get_news,
    search_news_observations,
)
from .pat2vec_get_methods.get_method_obs import (
    get_current_pat_obs,
)
from .pat2vec_get_methods.get_method_pat_annotations import (
    get_current_pat_annotations,
)
from .pat2vec_get_methods.get_method_problem_list import (
    get_current_pat_problem_list,
)
from .pat2vec_get_methods.get_method_report_annotations import (
    get_current_pat_report_annotations,
)
from .pat2vec_get_methods.get_method_smoking import (
    SMOKING_FIELDS,
    calculate_smoking_features,
    get_smoking,
    prepare_smoking_data,
    search_smoking,
)
from .pat2vec_get_methods.get_method_textual_obs_annotations import (
    get_current_pat_textual_obs_annotations,
)
from .pat2vec_get_methods.get_method_vte_status import (
    VTE_FIELDS,
    calculate_vte_features,
    get_vte_status,
    prepare_vte_data,
    search_vte,
)
from .pat2vec_get_methods.test_get_method_demo import (
    TestGetMethodDemo,
)
from .pat2vec_main_methods.main_batch import (
    main_batch,
)
from .pat2vec_pat_list.get_patient_treatment_list import (
    analyze_client_codes,
    extract_treatment_id_list_from_docs,
    generate_control_list,
    get_all_patients_list,
    sanitize_hospital_ids,
)
from .pat2vec_search.cogstack_search_methods import (
    CogStack,
    check_patients_existence,
    cohort_searcher_no_terms,
    cohort_searcher_no_terms_fuzzy,
    cohort_searcher_with_terms_and_search,
    cohort_searcher_with_terms_no_search,
    create_credentials_file,
    dataframe_generator,
    get_all_fields_for_method,
    initialize_cogstack_client,
    iterative_multi_term_cohort_searcher_no_terms_fuzzy,
    iterative_multi_term_cohort_searcher_no_terms_fuzzy_diagnostics,
    iterative_multi_term_cohort_searcher_no_terms_fuzzy_drugs,
    iterative_multi_term_cohort_searcher_no_terms_fuzzy_epic_clinical_notes,
    iterative_multi_term_cohort_searcher_no_terms_fuzzy_epic_clinical_notes_appointments,
    iterative_multi_term_cohort_searcher_no_terms_fuzzy_epic_encounters,
    iterative_multi_term_cohort_searcher_no_terms_fuzzy_epic_imaging_reports,
    iterative_multi_term_cohort_searcher_no_terms_fuzzy_epic_lab_results,
    iterative_multi_term_cohort_searcher_no_terms_fuzzy_epic_medical_history,
    iterative_multi_term_cohort_searcher_no_terms_fuzzy_epic_orders,
    iterative_multi_term_cohort_searcher_no_terms_fuzzy_mct,
    iterative_multi_term_cohort_searcher_no_terms_fuzzy_obs,
    iterative_multi_term_cohort_searcher_no_terms_fuzzy_reports,
    iterative_multi_term_cohort_searcher_no_terms_fuzzy_textual_obs,
    list_chunker,
    set_index_safe_wrapper,
)
from .pat2vec_search.data_helper_functions import (
    appendAge,
    appendAgeAtRecord,
    append_age_at_record_series,
    df_column_uniquify,
)
from .pat2vec_search.matcher import (
    find_all_matches,
    match_terms_in_text,
    matcher,
)
from .pat2vec_search.nearest import (
    nearest,
)
from .pat2vec_search.search_helper_functions import (
    bulk_str_extract,
    bulk_str_extract_round_robin,
    bulk_str_findall,
    date_cleaner,
    pylist2searchlist,
    stringlist2pylist,
    stringlist2searchlist,
    without_keys,
)
from .pat2vec_search.search_multiprocess import (
    cohort_searcher_with_terms_and_search_multi,
    pull_and_write,
)
from .pat2vec_search.test_cogstack_search_methods import (
    TestCogstackSearchMethods,
)
from .pat2vec_search.test_data_helper_functions import (
    TestDataHelperFunctions,
)
from .pat2vec_search.test_matcher import (
    TestMatcher,
)
from .patvec_get_batch_methods.get_merged_batches import (
    get_merged_pat_batch_appointments,
    get_merged_pat_batch_bloods,
    get_merged_pat_batch_bmi,
    get_merged_pat_batch_demo,
    get_merged_pat_batch_diagnostics,
    get_merged_pat_batch_drugs,
    get_merged_pat_batch_epr_docs,
    get_merged_pat_batch_mct_docs,
    get_merged_pat_batch_news,
    get_merged_pat_batch_obs,
    get_merged_pat_batch_reports,
    get_merged_pat_batch_textual_obs_docs,
    save_group,
    split_and_save_csv,
    verify_split_data_concatenated,
    verify_split_data_individual,
)
from .patvec_get_batch_methods.get_prefetch_batches import (
    BatchConfig,
    prefetch_batches,
)
from .patvec_get_batch_methods.main_get_pat_batch_appointments import (
    get_pat_batch_appointments,
)
from .patvec_get_batch_methods.main_get_pat_batch_bloods import (
    get_pat_batch_bloods,
)
from .patvec_get_batch_methods.main_get_pat_batch_bmi import (
    get_pat_batch_bmi,
)
from .patvec_get_batch_methods.main_get_pat_batch_demo import (
    get_pat_batch_demo,
)
from .patvec_get_batch_methods.main_get_pat_batch_diagnostics import (
    get_pat_batch_diagnostics,
)
from .patvec_get_batch_methods.main_get_pat_batch_drugs import (
    get_pat_batch_drugs,
)
from .patvec_get_batch_methods.main_get_pat_batch_epr_docs import (
    get_pat_batch_epr_docs,
)
from .patvec_get_batch_methods.main_get_pat_batch_epr_docs_annotations import (
    get_pat_batch_epr_docs_annotations,
)
from .patvec_get_batch_methods.main_get_pat_batch_mct_docs import (
    get_pat_batch_mct_docs,
)
from .patvec_get_batch_methods.main_get_pat_batch_mct_docs_annotations import (
    get_pat_batch_mct_docs_annotations,
)
from .patvec_get_batch_methods.main_get_pat_batch_news import (
    get_pat_batch_news,
)
from .patvec_get_batch_methods.main_get_pat_batch_obs import (
    get_pat_batch_obs,
)
from .patvec_get_batch_methods.main_get_pat_batch_reports import (
    get_pat_batch_reports,
)
from .patvec_get_batch_methods.main_get_pat_batch_reports_docs_annotations import (
    get_pat_batch_reports_docs_annotations,
)
from .patvec_get_batch_methods.main_get_pat_batch_textual_obs_annotations import (
    get_pat_batch_textual_obs_annotations,
)
from .patvec_get_batch_methods.main_get_pat_batch_textual_obs_docs import (
    get_pat_batch_textual_obs_docs,
)
from .util.anonymisation_data_methods import (
    anonymize_feature_names,
    deanonymize_feature_names,
)
from .util.anonymisation_deid_documents import (
    DeIdAnonymizer,
    anonymize_dataframe_quick,
    anonymize_single_text,
)
from .util.calculate_interval import (
    calculate_interval,
)
from .util.clinical_note_splitter import (
    find_date,
    split_and_append_chunks,
    split_clinical_notes,
    split_clinical_notes_mct,
    split_epic_clinical_notes,
)
from .util.compile_requirements import (
    append_to_file,
    process_requirements,
    run_pip_compile,
)
from .util.config_pat2vec import (
    config_class,
    update_global_start_date,
    validate_and_fix_global_dates,
)
from .util.current_pat_batch_path_methods import (
    PathsClass,
)
from .util.docker_elastic import (
    ElasticContainer,
)
from .util.elasticsearch_methods import (
    get_guess_datetime_column,
    guess_datetime_columns,
    handle_inconsistent_dtypes,
    ingest_data_to_elasticsearch,
)
from .util.ethnicity_abstractor import (
    EthnicityAbstractor,
)
from .util.evaluation_methods import (
    CsvProfiler,
    compare_ipw_annotation_rows,
)
from .util.evaluation_methods_ploting import (
    generate_pie_charts,
    plot_calibration_curve,
    plot_confusion_matrix,
    plot_feature_importance,
    plot_missing_data_patterns,
    plot_precision_recall_curve,
    plot_roc_curve,
)
from .util.filter_dataframe_by_timestamp import (
    filter_dataframe_by_timestamp,
)
from .util.filter_methods import (
    apply_bloods_data_type_filter,
    apply_data_type_diagnostics_filters,
    apply_data_type_drugs_filters,
    apply_data_type_epic_clinical_notes_appointments_filters,
    apply_data_type_epic_clinical_notes_filters,
    apply_data_type_epic_imaging_reports_filters,
    apply_data_type_epic_lab_results_filters,
    apply_data_type_epic_medical_history_filters,
    apply_data_type_epic_orders_filters,
    apply_data_type_epic_patients_filters,
    apply_data_type_epr_docs_filters,
    apply_data_type_mct_docs_filters,
    apply_data_type_news_filters,
    apply_data_type_obs_filters,
    apply_data_type_reports_filters,
    apply_data_type_textual_obs_filters,
    filter_dataframe_by_fuzzy_terms,
)
from .util.generate_date_list import (
    generate_date_list,
)
from .util.generate_elastic_schema import (
    create_schema_from_dataframe,
    generate_elastic_schema,
    generate_mapping_for_dataframe,
    generate_schema_from_cluster,
)
from .util.get_best_gpu import (
    set_best_gpu,
)
from .util.get_dummy_data_cohort_searcher import (
    cohort_searcher_with_terms_and_search_dummy,
    create_random_date_from_globals,
    dummy_CAT,
    extract_date_range,
    extract_search_term_obscatalogmasteritem_displayname,
    generate_appointments_data,
    generate_basic_observations_data,
    generate_basic_observations_textual_obs_data,
    generate_bed_data,
    generate_bmi_data,
    generate_core_o2_data,
    generate_core_resus_data,
    generate_covid_observations_data,
    generate_diagnostic_orders_data,
    generate_drug_orders_data,
    generate_epic_clinical_notes_appointments_data,
    generate_epic_clinical_notes_data,
    generate_epic_encounters_data,
    generate_epic_imaging_reports_data,
    generate_epic_lab_results_data,
    generate_epic_medical_history_data,
    generate_epic_orders_data,
    generate_epic_patients_data,
    generate_epr_documents_data,
    generate_epr_documents_personal_data,
    generate_hospital_site_data,
    generate_news_data,
    generate_observations_MRC_text_data,
    generate_observations_Reports_text_data,
    generate_observations_data,
    generate_patient_timeline,
    generate_patient_timeline_faker,
    generate_problem_list_data,
    generate_smoking_data,
    generate_uuid,
    generate_uuid_list,
    generate_vte_data,
    get_patient_timeline_dummy,
    is_safe_host,
    maybe_nan,
    populate_elastic_with_dummy_data,
    run_generate_patient_timeline_and_append,
)
from .util.get_dummy_data_medcat_annotation import (
    augment_dummy_annotations_file,
    dummy_medcat_annotation_generator,
    random_sample,
)
from .util.get_method_default_fields_map import (
    GET_METHOD_DEFAULT_FIELDS_MAP,
    get_all_method_default_fields,
    get_default_fields_for_method,
)
from .util.get_method_index_map import (
    GET_METHOD_INDEX_MAP,
    get_all_method_indices,
    get_index_for_method,
)
from .util.get_start_end_year_month import (
    get_start_end_year_month,
)
from .util.helper_functions import (
    HELPER_FUNCTIONS_VERSION,
    clear_patient_features,
    ensure_index,
    extract_nhs_numbers,
    get_all_features,
    get_df_from_db,
    get_ram_usage,
    get_search_client_idcode_list_from_nhs_number_list,
    sanitize_for_path,
    save_annotations_to_db,
    save_patient_features,
    save_raw_patient_batch,
    try_parse_list_string,
)
from .util.impute_data_for_pipe import (
    mean_impute_dataframe,
    save_missing_percentage,
)
from .util.logger_setup import (
    setup_logger,
)
from .util.medcat_misc_methods import (
    create_ner_results_dataframe,
    extract_labels_from_medcat_annotation_export,
    manually_label_annotation_df,
    medcat_trainer_export_to_df,
    parse_medcat_trainer_project_json,
    plot_ner_results,
    recreate_json,
)
from .util.methods_annotation import (
    annot_pat_batch_docs,
    calculate_pretty_name_count_features,
    check_pat_document_annotation_complete,
    multi_annots_to_df_epic_clinical_notes,
    multi_annots_to_df_epic_clinical_notes_appointments,
    multi_annots_to_df_epic_imaging_reports,
    multi_annots_to_df_epic_lab_results,
    multi_annots_to_df_epic_medical_history,
    multi_annots_to_df_epic_orders,
    multi_annots_to_df_epr_docs,
    multi_annots_to_df_mct,
    multi_annots_to_df_reports,
    multi_annots_to_df_textual_obs,
)
from .util.methods_annotation_filter_annot_dataframe import (
    filter_annot_dataframe,
)
from .util.methods_annotation_get_pat_document_annotation_batch import (
    get_pat_batch_textual_obs_annotation_batch,
    get_pat_document_annotation_batch,
    get_pat_document_annotation_batch_epic_clinical_notes,
    get_pat_document_annotation_batch_epic_clinical_notes_appointments,
    get_pat_document_annotation_batch_epic_imaging_reports,
    get_pat_document_annotation_batch_epic_medical_history,
    get_pat_document_annotation_batch_mct,
    get_pat_document_annotation_batch_reports,
)
from .util.methods_annotation_json_to_dataframe import (
    json_to_dataframe,
    parse_meta_anns,
)
from .util.methods_annotation_multi_annots_to_df import (
    multi_annots_to_df,
    temporary_file,
)
from .util.methods_annotation_regex import (
    append_regex_term_counts,
)
from .util.methods_get import (
    add_offset_column,
    build_patient_dict,
    convert_date,
    convert_timestamp_to_tuple,
    create_folders,
    create_folders_annot_csv_wrapper,
    create_folders_for_pat,
    create_local_folders,
    create_remote_folders,
    dump_results,
    enum_exact_target_date_vector,
    enum_target_date_vector,
    exist_check,
    filter_stripped_list,
    get_empty_date_vector,
    get_free_gpu,
    list_dir_wrapper,
    read_csv_wrapper,
    read_remote,
    sftp_exists,
    test_datetime_formats,
    update_pbar,
    write_csv_wrapper,
    write_remote,
)
from .util.methods_get_medcat import (
    get_cat,
)
from .util.methods_post_get import (
    check_csv_files_in_directory,
    check_csv_integrity,
    copy_project_folders_with_substring_match,
    retrieve_pat_annotations,
)
from .util.migrate_to_db import (
    MAPPINGS,
    create_indexes,
    migrate_csv_to_db,
)
from .util.parse_date import (
    validate_input_dates,
)
from .util.post_processing_annotations import (
    EMPTY_ANNOT_COLS,
    check_list_presence,
    extract_types_from_csv,
    filter_and_select_rows,
    filter_annot_dataframe2,
    filter_dataframe_by_cui,
    filter_dataframe_n_lists,
    get_all_target_annots,
    join_icd10_OPC4S_codes_to_annot,
    join_icd10_codes_to_annot,
    produce_filtered_annotation_dataframe,
    remove_file_from_paths,
    retrieve_pat_annots_mct_epr,
)
from .util.post_processing_build_ipw_dataframe import (
    build_ipw_dataframe,
)
from .util.post_processing_build_methods import (
    build_merged_bloods,
    build_merged_epr_mct_annot_df,
    build_merged_epr_mct_doc_df,
    get_annots_joined_to_docs,
    join_docs_to_annots,
    load_merged_epr_mct_annots,
    merge_appointments_csv,
    merge_bed_csv,
    merge_bloods_csv,
    merge_bmi_csv,
    merge_core_02_csv,
    merge_core_resus_csv,
    merge_covid_csv,
    merge_demographics_csv,
    merge_diagnostics_csv,
    merge_drugs_csv,
    merge_epic_clinical_notes_appointments_csv,
    merge_epic_clinical_notes_csv,
    merge_epic_encounters_csv,
    merge_epic_imaging_reports_csv,
    merge_epic_lab_results_csv,
    merge_epic_medical_history_csv,
    merge_epic_orders_csv,
    merge_epic_patients_csv,
    merge_hosp_site_csv,
    merge_news_csv,
    merge_reports_csv,
    merge_smoking_csv,
    merge_textual_obs_csv,
    merge_vte_status_csv,
    optimize_dtypes,
    retrieve_pat_bloods,
    retrieve_pat_docs_mct_epr,
    retrieve_pat_epr_docs,
)
from .util.post_processing_dataframe import (
    aggregate_dataframe_mean,
    collapse_df_to_mean,
    convert_true_to_float,
    drop_columns_with_all_nan,
    extract_datetime_from_binary_columns,
    extract_datetime_from_binary_columns_chunk_reader,
    extract_datetime_to_column,
    impute_dataframe,
    impute_datetime,
    missing_percentage_df,
    save_missing_values_pickle,
)
from .util.post_processing_get_pat_ipw_record import (
    get_pat_ipw_record,
)
from .util.post_processing_medcat import (
    coerce_document_df_to_medcat_trainer_input,
    sample_by_terms,
)
from .util.post_processing_plotting import (
    plot_missing_pattern_bloods,
)
from .util.post_processing_process_csv_files import (
    process_csv_files,
    process_csv_files_multi,
)
from .util.post_processing_utils import (
    copy_files_and_dirs,
    count_files,
    filter_and_update_csv,
    process_chunk,
)
from .util.pre_get_drug_treatment_docs import (
    get_treatment_records_by_drug_order_name,
    get_treatment_records_by_drug_order_name_epic,
    iterative_drug_treatment_search,
)
from .util.pre_processing import (
    calculate_age_append,
    demo_to_latest,
    draw_document_samples,
    get_all_patient_list,
    get_treatment_docs_by_iterative_multi_term_cohort_searcher_no_terms_fuzzy,
    search_cohort,
)
from .util.presentation_methods import (
    create_powerpoint_from_images,
    create_powerpoint_from_images_group,
    create_powerpoint_slides,
    create_powerpoint_slides_client_idcode_groups,
    group_images_by_suffix,
)
from .util.retrieve_data import (
    DATA_TYPE_CONFIG,
    retrieve_patient_data,
)
from .util.testing_helpers import (
    read_test_data,
)

# Define the public API of the package
__all__ = [
    "APPOINTMENT_FIELDS",
    "BED_FIELDS",
    "BLOODS_FIELDS",
    "BMI_FIELDS",
    "BatchConfig",
    "COLUMNS_TO_DROP",
    "CORE_O2_FIELDS",
    "CORE_RESUS_FIELDS",
    "COVID_FIELDS",
    "CogStack",
    "CsvProfiler",
    "DATA_TYPE_CONFIG",
    "DEMOGRAPHICS_FIELDS",
    "DIAGNOSTICS_FIELDS",
    "DRUG_FIELDS",
    "DeIdAnonymizer",
    "EMPTY_ANNOT_COLS",
    "EPIC_CLINICAL_NOTES_APPOINTMENTS_FIELDS",
    "EPIC_CLINICAL_NOTES_FIELDS",
    "EPIC_ENCOUNTER_FIELDS",
    "EPIC_IMAGING_REPORTS_FIELDS",
    "EPIC_LAB_RESULTS_FIELDS",
    "EPIC_MEDICAL_HISTORY_FIELDS",
    "EPIC_ORDERS_FIELDS",
    "EPIC_PATIENTS_FIELDS",
    "ElasticContainer",
    "EthnicityAbstractor",
    "GET_METHOD_DEFAULT_FIELDS_MAP",
    "GET_METHOD_INDEX_MAP",
    "HELPER_FUNCTIONS_VERSION",
    "HOSP_SITE_FIELDS",
    "MAPPINGS",
    "PathsClass",
    "SEARCH_TERM",
    "SEARCH_TERM_ES",
    "SEARCH_TERM_PLAIN",
    "SMOKING_FIELDS",
    "TestCogstackSearchMethods",
    "TestDataHelperFunctions",
    "TestGetMethodDemo",
    "TestMatcher",
    "VTE_FIELDS",
    "add_offset_column",
    "aggregate_dataframe_mean",
    "analyze_client_codes",
    "annot_pat_batch_docs",
    "anonymize_dataframe_quick",
    "anonymize_feature_names",
    "anonymize_single_text",
    "appendAge",
    "appendAgeAtRecord",
    "append_age_at_record_series",
    "append_regex_term_counts",
    "append_to_file",
    "apply_bloods_data_type_filter",
    "apply_data_type_diagnostics_filters",
    "apply_data_type_drugs_filters",
    "apply_data_type_epic_clinical_notes_appointments_filters",
    "apply_data_type_epic_clinical_notes_filters",
    "apply_data_type_epic_imaging_reports_filters",
    "apply_data_type_epic_lab_results_filters",
    "apply_data_type_epic_medical_history_filters",
    "apply_data_type_epic_orders_filters",
    "apply_data_type_epic_patients_filters",
    "apply_data_type_epr_docs_filters",
    "apply_data_type_mct_docs_filters",
    "apply_data_type_news_filters",
    "apply_data_type_obs_filters",
    "apply_data_type_reports_filters",
    "apply_data_type_textual_obs_filters",
    "augment_dummy_annotations_file",
    "build_ipw_dataframe",
    "build_merged_bloods",
    "build_merged_epr_mct_annot_df",
    "build_merged_epr_mct_doc_df",
    "build_patient_dict",
    "bulk_str_extract",
    "bulk_str_extract_round_robin",
    "bulk_str_findall",
    "calculate_age_append",
    "calculate_bmi_features",
    "calculate_core_o2_features",
    "calculate_core_resus_features",
    "calculate_covid_features",
    "calculate_diagnostic_features",
    "calculate_drug_features",
    "calculate_hospital_site_features",
    "calculate_interval",
    "calculate_pretty_name_count_features",
    "calculate_smoking_features",
    "calculate_vte_features",
    "check_csv_files_in_directory",
    "check_csv_integrity",
    "check_list_presence",
    "check_pat_document_annotation_complete",
    "check_patients_existence",
    "clean_observation_value",
    "clear_patient_features",
    "coerce_document_df_to_medcat_trainer_input",
    "cohort_searcher_no_terms",
    "cohort_searcher_no_terms_fuzzy",
    "cohort_searcher_with_terms_and_search",
    "cohort_searcher_with_terms_and_search_dummy",
    "cohort_searcher_with_terms_and_search_multi",
    "cohort_searcher_with_terms_no_search",
    "collapse_df_to_mean",
    "compare_ipw_annotation_rows",
    "compute_feature_stats",
    "config_class",
    "convert_date",
    "convert_timestamp_to_tuple",
    "convert_true_to_float",
    "copy_files_and_dirs",
    "copy_project_folders_with_substring_match",
    "count_files",
    "create_credentials_file",
    "create_diagnostic_features_dataframe",
    "create_drug_features_dataframe",
    "create_folders",
    "create_folders_annot_csv_wrapper",
    "create_folders_for_pat",
    "create_indexes",
    "create_local_folders",
    "create_ner_results_dataframe",
    "create_powerpoint_from_images",
    "create_powerpoint_from_images_group",
    "create_powerpoint_slides",
    "create_powerpoint_slides_client_idcode_groups",
    "create_random_date_from_globals",
    "create_remote_folders",
    "create_schema_from_dataframe",
    "dataframe_generator",
    "date_cleaner",
    "deanonymize_feature_names",
    "demo_to_latest",
    "df_column_uniquify",
    "draw_document_samples",
    "drop_columns_with_all_nan",
    "dummy_CAT",
    "dummy_medcat_annotation_generator",
    "dump_results",
    "ensure_index",
    "enum_exact_target_date_vector",
    "enum_target_date_vector",
    "exist_check",
    "extract_date_range",
    "extract_datetime_from_binary_columns",
    "extract_datetime_from_binary_columns_chunk_reader",
    "extract_datetime_to_column",
    "extract_labels_from_medcat_annotation_export",
    "extract_nhs_numbers",
    "extract_search_term_obscatalogmasteritem_displayname",
    "extract_treatment_id_list_from_docs",
    "extract_types_from_csv",
    "filter_and_select_rows",
    "filter_and_update_csv",
    "filter_annot_dataframe",
    "filter_annot_dataframe2",
    "filter_dataframe_by_cui",
    "filter_dataframe_by_fuzzy_terms",
    "filter_dataframe_by_timestamp",
    "filter_dataframe_n_lists",
    "filter_stripped_list",
    "find_all_matches",
    "find_date",
    "generate_appointments_data",
    "generate_basic_observations_data",
    "generate_basic_observations_textual_obs_data",
    "generate_bed_data",
    "generate_bmi_data",
    "generate_control_list",
    "generate_core_o2_data",
    "generate_core_resus_data",
    "generate_covid_observations_data",
    "generate_date_list",
    "generate_diagnostic_orders_data",
    "generate_drug_orders_data",
    "generate_elastic_schema",
    "generate_epic_clinical_notes_appointments_data",
    "generate_epic_clinical_notes_data",
    "generate_epic_encounters_data",
    "generate_epic_imaging_reports_data",
    "generate_epic_lab_results_data",
    "generate_epic_medical_history_data",
    "generate_epic_orders_data",
    "generate_epic_patients_data",
    "generate_epr_documents_data",
    "generate_epr_documents_personal_data",
    "generate_hospital_site_data",
    "generate_mapping_for_dataframe",
    "generate_news_data",
    "generate_observations_MRC_text_data",
    "generate_observations_Reports_text_data",
    "generate_observations_data",
    "generate_patient_timeline",
    "generate_patient_timeline_faker",
    "generate_pie_charts",
    "generate_problem_list_data",
    "generate_schema_from_cluster",
    "generate_smoking_data",
    "generate_uuid",
    "generate_uuid_list",
    "generate_vte_data",
    "get_all_features",
    "get_all_fields_for_method",
    "get_all_method_default_fields",
    "get_all_method_indices",
    "get_all_patient_list",
    "get_all_patients_list",
    "get_all_target_annots",
    "get_annots_joined_to_docs",
    "get_appointments",
    "get_bed",
    "get_bmi_features",
    "get_cat",
    "get_core_02",
    "get_core_resus",
    "get_covid",
    "get_current_pat_annotations",
    "get_current_pat_annotations_mrc_cs",
    "get_current_pat_bloods",
    "get_current_pat_diagnostics",
    "get_current_pat_drugs",
    "get_current_pat_epic_orders_annotations",
    "get_current_pat_obs",
    "get_current_pat_problem_list",
    "get_current_pat_report_annotations",
    "get_current_pat_textual_obs_annotations",
    "get_default_fields_for_method",
    "get_demo",
    "get_demographics3",
    "get_demographics3_batch",
    "get_demographics_data",
    "get_df_from_db",
    "get_empty_date_vector",
    "get_epic_clinical_notes",
    "get_epic_clinical_notes_appointments",
    "get_epic_encounters",
    "get_epic_imaging_reports",
    "get_epic_lab_results",
    "get_epic_medical_history",
    "get_epic_orders",
    "get_epic_patients",
    "get_free_gpu",
    "get_guess_datetime_column",
    "get_hosp_site",
    "get_index_for_method",
    "get_merged_pat_batch_appointments",
    "get_merged_pat_batch_bloods",
    "get_merged_pat_batch_bmi",
    "get_merged_pat_batch_demo",
    "get_merged_pat_batch_diagnostics",
    "get_merged_pat_batch_drugs",
    "get_merged_pat_batch_epr_docs",
    "get_merged_pat_batch_mct_docs",
    "get_merged_pat_batch_news",
    "get_merged_pat_batch_obs",
    "get_merged_pat_batch_reports",
    "get_merged_pat_batch_textual_obs_docs",
    "get_news",
    "get_pat_batch_appointments",
    "get_pat_batch_bloods",
    "get_pat_batch_bmi",
    "get_pat_batch_demo",
    "get_pat_batch_diagnostics",
    "get_pat_batch_drugs",
    "get_pat_batch_epr_docs",
    "get_pat_batch_epr_docs_annotations",
    "get_pat_batch_mct_docs",
    "get_pat_batch_mct_docs_annotations",
    "get_pat_batch_news",
    "get_pat_batch_obs",
    "get_pat_batch_reports",
    "get_pat_batch_reports_docs_annotations",
    "get_pat_batch_textual_obs_annotation_batch",
    "get_pat_batch_textual_obs_annotations",
    "get_pat_batch_textual_obs_docs",
    "get_pat_document_annotation_batch",
    "get_pat_document_annotation_batch_epic_clinical_notes",
    "get_pat_document_annotation_batch_epic_clinical_notes_appointments",
    "get_pat_document_annotation_batch_epic_imaging_reports",
    "get_pat_document_annotation_batch_epic_medical_history",
    "get_pat_document_annotation_batch_mct",
    "get_pat_document_annotation_batch_reports",
    "get_pat_ipw_record",
    "get_patient_timeline_dummy",
    "get_ram_usage",
    "get_search_client_idcode_list_from_nhs_number_list",
    "get_smoking",
    "get_start_end_year_month",
    "get_treatment_docs_by_iterative_multi_term_cohort_searcher_no_terms_fuzzy",
    "get_treatment_records_by_drug_order_name",
    "get_treatment_records_by_drug_order_name_epic",
    "get_vte_status",
    "group_images_by_suffix",
    "guess_datetime_columns",
    "handle_inconsistent_dtypes",
    "impute_dataframe",
    "impute_datetime",
    "ingest_data_to_elasticsearch",
    "initialize_cogstack_client",
    "is_safe_host",
    "iterative_drug_treatment_search",
    "iterative_multi_term_cohort_searcher_no_terms_fuzzy",
    "iterative_multi_term_cohort_searcher_no_terms_fuzzy_diagnostics",
    "iterative_multi_term_cohort_searcher_no_terms_fuzzy_drugs",
    "iterative_multi_term_cohort_searcher_no_terms_fuzzy_epic_clinical_notes",
    "iterative_multi_term_cohort_searcher_no_terms_fuzzy_epic_clinical_notes_appointments",
    "iterative_multi_term_cohort_searcher_no_terms_fuzzy_epic_encounters",
    "iterative_multi_term_cohort_searcher_no_terms_fuzzy_epic_imaging_reports",
    "iterative_multi_term_cohort_searcher_no_terms_fuzzy_epic_lab_results",
    "iterative_multi_term_cohort_searcher_no_terms_fuzzy_epic_medical_history",
    "iterative_multi_term_cohort_searcher_no_terms_fuzzy_epic_orders",
    "iterative_multi_term_cohort_searcher_no_terms_fuzzy_mct",
    "iterative_multi_term_cohort_searcher_no_terms_fuzzy_obs",
    "iterative_multi_term_cohort_searcher_no_terms_fuzzy_reports",
    "iterative_multi_term_cohort_searcher_no_terms_fuzzy_textual_obs",
    "join_docs_to_annots",
    "join_icd10_OPC4S_codes_to_annot",
    "join_icd10_codes_to_annot",
    "json_to_dataframe",
    "list_chunker",
    "list_dir_wrapper",
    "load_merged_epr_mct_annots",
    "main",
    "main_batch",
    "manually_label_annotation_df",
    "match_terms_in_text",
    "matcher",
    "maybe_nan",
    "mean_impute_dataframe",
    "medcat_trainer_export_to_df",
    "merge_appointments_csv",
    "merge_bed_csv",
    "merge_bloods_csv",
    "merge_bmi_csv",
    "merge_core_02_csv",
    "merge_core_resus_csv",
    "merge_covid_csv",
    "merge_demographics_csv",
    "merge_diagnostics_csv",
    "merge_drugs_csv",
    "merge_epic_clinical_notes_appointments_csv",
    "merge_epic_clinical_notes_csv",
    "merge_epic_encounters_csv",
    "merge_epic_imaging_reports_csv",
    "merge_epic_lab_results_csv",
    "merge_epic_medical_history_csv",
    "merge_epic_orders_csv",
    "merge_epic_patients_csv",
    "merge_hosp_site_csv",
    "merge_news_csv",
    "merge_reports_csv",
    "merge_smoking_csv",
    "merge_textual_obs_csv",
    "merge_vte_status_csv",
    "migrate_csv_to_db",
    "missing_percentage_df",
    "multi_annots_to_df",
    "multi_annots_to_df_epic_clinical_notes",
    "multi_annots_to_df_epic_clinical_notes_appointments",
    "multi_annots_to_df_epic_imaging_reports",
    "multi_annots_to_df_epic_lab_results",
    "multi_annots_to_df_epic_medical_history",
    "multi_annots_to_df_epic_orders",
    "multi_annots_to_df_epr_docs",
    "multi_annots_to_df_mct",
    "multi_annots_to_df_reports",
    "multi_annots_to_df_textual_obs",
    "nearest",
    "optimize_dtypes",
    "parse_medcat_trainer_project_json",
    "parse_meta_anns",
    "plot_calibration_curve",
    "plot_confusion_matrix",
    "plot_feature_importance",
    "plot_missing_data_patterns",
    "plot_missing_pattern_bloods",
    "plot_ner_results",
    "plot_precision_recall_curve",
    "plot_roc_curve",
    "populate_elastic_with_dummy_data",
    "prefetch_batches",
    "prepare_diagnostic_datetime",
    "prepare_drug_datetime",
    "prepare_hospital_site_data",
    "prepare_smoking_data",
    "prepare_vte_data",
    "process_chunk",
    "process_csv_files",
    "process_csv_files_multi",
    "process_demographics_data",
    "process_requirements",
    "produce_filtered_annotation_dataframe",
    "pull_and_write",
    "pylist2searchlist",
    "random_sample",
    "read_csv_wrapper",
    "read_remote",
    "read_test_data",
    "recreate_json",
    "remove_file_from_paths",
    "retrieve_pat_annotations",
    "retrieve_pat_annots_mct_epr",
    "retrieve_pat_bloods",
    "retrieve_pat_docs_mct_epr",
    "retrieve_pat_epr_docs",
    "retrieve_patient_data",
    "run_generate_patient_timeline_and_append",
    "run_pip_compile",
    "sample_by_terms",
    "sanitize_for_path",
    "sanitize_hospital_ids",
    "save_annotations_to_db",
    "save_group",
    "save_missing_percentage",
    "save_missing_values_pickle",
    "save_patient_features",
    "save_raw_patient_batch",
    "search_appointments",
    "search_bed_data",
    "search_bloods_data",
    "search_bmi_observations",
    "search_cohort",
    "search_core_o2_observations",
    "search_core_resus_observations",
    "search_covid",
    "search_demographics",
    "search_diagnostic_orders",
    "search_drug_orders",
    "search_epic_clinical_notes",
    "search_epic_clinical_notes_appointments",
    "search_epic_encounters",
    "search_epic_imaging_reports",
    "search_epic_lab_results",
    "search_epic_medical_history",
    "search_epic_orders",
    "search_epic_patients",
    "search_hospital_site",
    "search_news_observations",
    "search_smoking",
    "search_vte",
    "set_best_gpu",
    "set_index_safe_wrapper",
    "setup_logger",
    "sftp_exists",
    "split_and_append_chunks",
    "split_and_save_csv",
    "split_clinical_notes",
    "split_clinical_notes_mct",
    "split_epic_clinical_notes",
    "stringlist2pylist",
    "stringlist2searchlist",
    "temporary_file",
    "test_datetime_formats",
    "try_parse_list_string",
    "update_global_start_date",
    "update_pbar",
    "validate_and_fix_global_dates",
    "validate_input_dates",
    "verify_split_data_concatenated",
    "verify_split_data_individual",
    "without_keys",
    "write_csv_wrapper",
    "write_remote",
]
