from collections.abc import Callable

import pandas as pd

from pat2vec.util.filter_dataframe_by_timestamp import filter_dataframe_by_timestamp
from pat2vec.util.get_start_end_year_month import get_start_end_year_month
from pat2vec.util.methods_annotation import calculate_pretty_name_count_features
from pat2vec.util.methods_get import update_pbar


def get_current_pat_epic_clinical_notes_annotations(
    current_pat_client_id_code: str,
    target_date_range: tuple,
    epic_clinical_notes_annotations: pd.DataFrame | None,
    config_obj: object | None = None,
    t: object | None = None,
    cohort_searcher_with_terms_and_search: Callable | None = None,
    cat: object | None = None,
) -> pd.DataFrame:
    """Retrieves and processes Epic clinical notes annotations for a patient.

    This function filters a batch of pre-existing Epic clinical notes annotations
    (produced using MedCAT text annotation) for a specific patient within a given
    date range. It then calculates count-based features from the 'pretty_name' of
    the annotations, producing an annotation vector suitable for downstream analysis.

    These annotations are generated by applying MedCAT to extract named entities and
    concepts from clinical text, resulting in standardized annotations with pretty_name,
    cui (Concept Unique Identifier), and other metadata.

    Args:
        current_pat_client_id_code: The unique identifier for the patient.
        target_date_range: A tuple containing (start_date, end_date) defining
            the time period to filter annotations by.
        epic_clinical_notes_annotations: DataFrame containing Epic clinical notes
            annotations for a batch of patients..Must be pre-annotated using MedCAT
            and contain 'document_CreatedWhen' column for timestamp filtering,
            'pretty_name', 'cui' for feature extraction.
        config_obj: Configuration object with settings such as `verbosity` and
            `start_time`. Cannot be None.
        t: Optional progress bar object for updating status during processing.
            Defaults to None.
        cohort_searcher_with_terms_and_search: Placeholder for a cohort searcher
            function, unused in this implementation. Defaults to None.
        cat: The MedCAT object used for text annotation. This parameter is included
            for API consistency but may not be directly used if annotations are
            pre-computed. Defaults to None.

    Returns:
        pd.DataFrame: A DataFrame containing the calculated annotation features
            for the specified patient. If no annotations are found, returns a
            DataFrame with only the 'client_idcode' column.

    Args:
        current_pat_client_id_code: The unique identifier for the patient.
        target_date_range: A tuple containing (start_date, end_date) defining
            the time period to filter annotations by.
        epic_clinical_notes_annotations: DataFrame containing Epic clinical notes
            annotations for a batch of patients. Must contain 'document_CreatedWhen'
            column for timestamp filtering and 'pretty_name', 'cui' for feature
            extraction.
        config_obj: Configuration object with settings such as `verbosity` and
            `start_time`. Cannot be None.
        t: Optional progress bar object for updating status during processing.
            Defaults to None.
        cohort_searcher_with_terms_and_search: Placeholder for a cohort searcher
            function, unused in this implementation. Defaults to None.
        cat: Placeholder for a MedCAT object, unused in this implementation.
            Defaults to None.

    Returns:
        pd.DataFrame: A DataFrame containing the calculated annotation features
            for the specified patient. If no annotations are found, returns a
            DataFrame with only the 'client_idcode' column.

    Raises:
        ValueError: If `config_obj` is None.
        ValueError: If `epic_clinical_notes_annotations` is None.
        ValueError: If `current_pat_client_id_code` is None.
        ValueError: If `target_date_range` is None.

    """
    if config_obj is None:
        raise ValueError(
            "config_obj cannot be None. Please provide a valid configuration.",
        )
    if epic_clinical_notes_annotations is None:
        raise ValueError(
            "epic_clinical_notes_annotations cannot be None. Please provide a valid DataFrame.",
        )
    if current_pat_client_id_code is None:
        raise ValueError(
            "current_pat_client_id_code cannot be None. Please provide a valid client ID code.",
        )
    if target_date_range is None:
        raise ValueError(
            "target_date_range cannot be None. Please provide a valid target date range.",
        )

    start_time = config_obj.start_time

    p_bar_entry = "annotations_epic_clinical_notes"
    try:
        update_pbar(
            current_pat_client_id_code,
            start_time,
            0,
            p_bar_entry,
            t,
            config_obj,
            config_obj.skipped_counter,
        )
    except Exception:
        pass

    start_year, start_month, end_year, end_month, start_day, end_day = (
        get_start_end_year_month(target_date_range, config_obj=config_obj)
    )

    time_column = getattr(
        config_obj,
        "epic_clinical_notes_time_field",
        "document_CreatedWhen",
    )

    if (
        epic_clinical_notes_annotations is not None
        and not epic_clinical_notes_annotations.empty
    ):
        if time_column not in epic_clinical_notes_annotations.columns:
            alternative_columns = [
                "updatetime",
                "basicobs_entered",
                "observationdocument_recordeddtm",
                "document_CreatedWhen",
            ]
            found_col = None
            for alt_col in alternative_columns:
                if alt_col in epic_clinical_notes_annotations.columns:
                    found_col = alt_col
                    break

            if found_col and found_col != time_column:
                epic_clinical_notes_annotations = (
                    epic_clinical_notes_annotations.rename(
                        columns={found_col: time_column},
                    )
                )

        filtered_epic_clinical_notes_annotations = filter_dataframe_by_timestamp(
            epic_clinical_notes_annotations,
            start_year,
            start_month,
            end_year,
            end_month,
            start_day,
            end_day,
            time_column,
            dropna=True,
        )

        if len(filtered_epic_clinical_notes_annotations) > 0:
            processed_annotations = calculate_pretty_name_count_features(
                filtered_epic_clinical_notes_annotations,
                suffix="epic_clinical_notes",
            )
        else:
            processed_annotations = pd.DataFrame(
                data=[current_pat_client_id_code],
                columns=["client_idcode"],
            )

    else:
        processed_annotations = pd.DataFrame(
            data=[current_pat_client_id_code],
            columns=["client_idcode"],
        )

    if config_obj.verbosity >= 6:
        print(
            f"DEBUG: Processing epic_clinical_notes_annotations for patient {current_pat_client_id_code}",
        )
        print(f"Input annotations shape: {epic_clinical_notes_annotations.shape}")
        print(f"Time column used: {time_column}")

        if config_obj.verbosity >= 7:
            print("DEBUG: Filtering epic clinical notes annotations...")
            print(
                f"Start: {start_year}-{start_month}-{start_day}, End: {end_year}-{end_month}-{end_day}",
            )

        if processed_annotations is not None:
            print(f"Processed annotations shape: {processed_annotations.shape}")
            print(
                f"Processed columns (first 10): {processed_annotations.columns.tolist()[:10]}",
            )

    return processed_annotations
