from collections.abc import Callable

import pandas as pd

from pat2vec.util.filter_dataframe_by_timestamp import filter_dataframe_by_timestamp
from pat2vec.util.get_start_end_year_month import get_start_end_year_month
from pat2vec.util.methods_annotation import calculate_pretty_name_count_features
from pat2vec.util.methods_get import update_pbar


def _extract_problem_list_annotations(
    filtered_annotations: pd.DataFrame | None,
    patient_id: str,
    unique_names: list[str] | None,
) -> pd.DataFrame:
    """Extracts problem_list features from epic_medical_history annotations.

    Filters annotations that have document_ProblemListEpicId (problem list entries)
    and creates count-based features for them.
    """
    if filtered_annotations is None or filtered_annotations.empty:
        return pd.DataFrame(data=[patient_id], columns=["client_idcode"])

    # Check if document_ProblemListEpicId column exists
    if "document_ProblemListEpicId" not in filtered_annotations.columns:
        return pd.DataFrame(data=[patient_id], columns=["client_idcode"])

    # Filter only problem list entries (those with document_ProblemListEpicId populated)
    problem_list_mask = filtered_annotations["document_ProblemListEpicId"].notna()
    problem_list_annotations = filtered_annotations[problem_list_mask]

    if problem_list_annotations.empty:
        return pd.DataFrame(data=[patient_id], columns=["client_idcode"])

    # Count features based on pretty_name for problem list entries
    if unique_names is not None and len(unique_names) > 0:
        feature_columns = [
            f"problem_list_count_epic_medical_history_{name}" for name in unique_names
        ]
        result_df = pd.DataFrame(
            {"client_idcode": [patient_id], **{col: [0.0] for col in feature_columns}},
        )

        # Count actual occurrences
        if "pretty_name" in problem_list_annotations.columns:
            pretty_name_counts = problem_list_annotations["pretty_name"].value_counts()
            for name, count in pretty_name_counts.items():
                col_name = f"problem_list_count_epic_medical_history_{name}"
                if col_name in result_df.columns:
                    result_df[col_name] = count

        return result_df

    return pd.DataFrame(data=[patient_id], columns=["client_idcode"])


def get_current_pat_epic_medical_history_annotations(
    current_pat_client_id_code: str,
    target_date_range: tuple,
    epic_medical_history_annotations: pd.DataFrame | None,
    config_obj: object | None = None,
    t: object | None = None,
    cohort_searcher_with_terms_and_search: Callable | None = None,
    cat: object | None = None,
) -> pd.DataFrame:
    """Retrieves and processes Epic medical history annotations for a patient.

    This function filters a batch of pre-existing Epic medical history annotations
    (produced using MedCAT text annotation) for a specific patient within a given
    date range. It then calculates count-based features from the 'pretty_name' of
    the annotations, producing an annotation vector suitable for downstream analysis.

    These annotations are generated by applying MedCAT to extract named entities and
    concepts from medical history text (e.g., comments, diagnoses), resulting in
    standardized annotations with pretty_name, cui (Concept Unique Identifier),
    and other metadata.

    Args:
    ----
        current_pat_client_id_code: The unique identifier for the patient.
        target_date_range: A tuple containing (start_date, end_date) defining
            the time period to filter annotations by.
        epic_medical_history_annotations: DataFrame containing Epic medical history
            annotations for a batch of patients. Must be pre-annotated using MedCAT
            and contain 'updatetime' column for timestamp filtering,
            'pretty_name', 'cui' for feature extraction.
        config_obj: Configuration object with settings such as `verbosity` and
            `start_time`. Cannot be None.
        t: Optional progress bar object for updating status during processing.
            Defaults to None.
        cohort_searcher_with_terms_and_search: Placeholder for a cohort searcher
            function, unused in this implementation. Defaults to None.
        cat: The MedCAT object used for text annotation. This parameter is included
            for API consistency but may not be directly used if annotations are
            pre-computed. Defaults to None.

    Returns:
    -------
        pd.DataFrame: A DataFrame containing the calculated annotation features
            for the specified patient. If no annotations are found, returns a
            DataFrame with only the 'client_idcode' column.

    Args:
    ----
        current_pat_client_id_code: The unique identifier for the patient.
        target_date_range: A tuple containing (start_date, end_date) defining
            the time period to filter annotations by.
        epic_medical_history_annotations: DataFrame containing Epic medical history
            annotations for a batch of patients. Must contain 'updatetime'
            column for timestamp filtering and 'pretty_name', 'cui' for feature
            extraction.
        config_obj: Configuration object with settings such as `verbosity` and
            `start_time`. Cannot be None.
        t: Optional progress bar object for updating status during processing.
            Defaults to None.
        cohort_searcher_with_terms_and_search: Placeholder for a cohort searcher
            function, unused in this implementation. Defaults to None.
        cat: Placeholder for a MedCAT object, unused in this implementation.
            Defaults to None.

    Returns:
    -------
        pd.DataFrame: A DataFrame containing the calculated annotation features
            for the specified patient. If no annotations are found, returns a
            DataFrame with only the 'client_idcode' column.

    Raises:
    ------
        ValueError: If `config_obj` is None.
        ValueError: If `epic_medical_history_annotations` is None.
        ValueError: If `current_pat_client_id_code` is None.
        ValueError: If `target_date_range` is None.

    """
    if config_obj is None:
        msg = "config_obj cannot be None. Please provide a valid configuration."
        raise ValueError(
            msg,
        )
    if epic_medical_history_annotations is None:
        msg = "epic_medical_history_annotations cannot be None. Please provide a valid DataFrame."
        raise ValueError(
            msg,
        )
    if current_pat_client_id_code is None:
        msg = "current_pat_client_id_code cannot be None. Please provide a valid client ID code."
        raise ValueError(
            msg,
        )
    if target_date_range is None:
        msg = "target_date_range cannot be None. Please provide a valid target date range."
        raise ValueError(
            msg,
        )

    start_time = config_obj.start_time

    p_bar_entry = "annotations_epic_medical_history"
    update_pbar(
        current_pat_client_id_code,
        start_time,
        0,
        p_bar_entry,
        t,
        config_obj,
        config_obj.skipped_counter,
    )

    start_year, start_month, end_year, end_month, start_day, end_day = (
        get_start_end_year_month(target_date_range, config_obj=config_obj)
    )

    time_column = getattr(
        config_obj,
        "epic_medical_history_time_field",
        "updatetime",
    )

    # Get all unique pretty names from the full batch for expected_names
    # This ensures even when filtered results are empty, we have consistent feature structure
    unique_pretty_names = None
    if (
        epic_medical_history_annotations is not None
        and not epic_medical_history_annotations.empty
        and "pretty_name" in epic_medical_history_annotations.columns
    ):
        unique_pretty_names = (
            epic_medical_history_annotations["pretty_name"].dropna().unique()
        )

    if (
        epic_medical_history_annotations is not None
        and not epic_medical_history_annotations.empty
    ):
        if time_column not in epic_medical_history_annotations.columns:
            alternative_columns = [
                "updatetime",
                "basicobs_entered",
                "observationdocument_recordeddtm",
                "document_UpdatedWhen",
            ]
            found_col = None
            for alt_col in alternative_columns:
                if alt_col in epic_medical_history_annotations.columns:
                    found_col = alt_col
                    break

            if found_col and found_col != time_column:
                epic_medical_history_annotations = (
                    epic_medical_history_annotations.rename(
                        columns={found_col: time_column},
                    )
                )

        filtered_epic_medical_history_annotations = filter_dataframe_by_timestamp(
            epic_medical_history_annotations,
            start_year,
            start_month,
            end_year,
            end_month,
            start_day,
            end_day,
            time_column,
            dropna=True,
        )

        if len(filtered_epic_medical_history_annotations) > 0:
            processed_annotations = calculate_pretty_name_count_features(
                filtered_epic_medical_history_annotations,
                suffix="epic_medical_history",
                patient_id=current_pat_client_id_code,
                expected_names=unique_pretty_names,
            )
        else:
            # When filtered annotations are empty, create feature DataFrame
            if unique_pretty_names is not None and len(unique_pretty_names) > 0:
                # Create zero-valued columns for each unique pretty_name from source
                feature_columns = [
                    f"pretty_name_count_epic_medical_history_{name}"
                    for name in unique_pretty_names
                ]
                processed_annotations = pd.DataFrame(
                    {
                        "client_idcode": [current_pat_client_id_code],
                        **{col: [0.0] for col in feature_columns},
                    },
                )
            else:
                # No pretty names available - return just client_idcode
                processed_annotations = pd.DataFrame(
                    data=[current_pat_client_id_code],
                    columns=["client_idcode"],
                )

    else:
        processed_annotations = pd.DataFrame(
            data=[current_pat_client_id_code],
            columns=["client_idcode"],
        )
        filtered_epic_medical_history_annotations = None

    # Extract problem_list features from epic_medical_history annotations
    # Problem list entries have document_ProblemListEpicId populated
    problem_list_features = _extract_problem_list_annotations(
        filtered_epic_medical_history_annotations,
        current_pat_client_id_code,
        unique_pretty_names,
    )
    if not problem_list_features.empty:
        processed_annotations = processed_annotations.merge(
            problem_list_features,
            on="client_idcode",
            how="left",
        )

    if config_obj.verbosity >= 6:
        print(
            f"Processing epic_medical_history_annotations for patient {current_pat_client_id_code}",
        )
        print(f"Input annotations shape: {epic_medical_history_annotations.shape}")
        print(f"Time column used: {time_column}")

        if config_obj.verbosity >= 7:
            print("Filtering epic medical history annotations...")
            print(
                f"Start: {start_year}-{start_month}-{start_day}, End: {end_year}-{end_month}-{end_day}",
            )

        if processed_annotations is not None:
            print(f"Processed annotations shape: {processed_annotations.shape}")
            print(
                f"Processed columns (first 10): {processed_annotations.columns.tolist()[:10]}",
            )

    return processed_annotations
